### ISSUE TITLE
Night mode doesn't like certain pages / sites

### ISSUE THREAD

**Issue by fluffynuts** [kiwibrowser/android#1]
I've only been using kiwi for a day, on the recommendation of a friend, and largely, the night mode is great. I prefer sites with less brightness, but people like my referring friend rely on features like that to navigate the web with sub-optimal vision. 

Anyways, I was linked to this site by Twitter: 
http://www.vulture.com/2018/06/a-complete-timeline-xxxtentacions-controversial-career.html
wherin, whilst using night mode, I simply got white text on a white background. I waited, thinking it might be some funky font downloading, but it wasn't readable until I turned night mode off. Please could you check it out - I'm assuming this could affect other sites too, though I haven't experienced it elsewhere.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
