### ISSUE TITLE
Update kiwi to chromium 76! 

### ISSUE THREAD

**Issue by LifeIsStrange** [kiwibrowser/android#102]
Chrome 77 will soon be released...

**Comment by x2k13** [comment]
I agree, what happened to "monthly updates"? Haven't seen one in 2 months now...

**Comment by hjyoung1** [comment]
Dev was on vacation he's back now. And he updated base to chromium 76.
![Screenshot_20190911_113750](https://user-images.githubusercontent.com/45882061/64672319-c65af000-d488-11e9-95c4-60b7438af1a6.png)
