### ISSUE TITLE
Gboard spell checker not work

### ISSUE THREAD

**Issue by andris155** [kiwibrowser/android#105]
The Gboard spell checker not work with Kiwi Browser.
On the Chrome works perfectly.

**Comment by andris155** [comment]
With Chrome see the underline
![Screenshot_20190914-231059_Chrome](https://user-images.githubusercontent.com/8324198/64913756-714c0200-d746-11e9-8c21-216bc121d103.png)

With Kiwi Browser
![Screenshot_20190914-231050_Kiwi_Browser](https://user-images.githubusercontent.com/8324198/64913760-8759c280-d746-11e9-869d-b48245d420df.png)

This is the Gboard spell check function.
![Screenshot_20190914-231655_Gboard](https://user-images.githubusercontent.com/8324198/64913761-8aed4980-d746-11e9-9a3e-3c526d5ed385.png)

**Comment by gggirlgeek** [comment]
Doesn't work with LeanKey keyboard in Firestick 4k either. Does spellcheck work for anyone else?
