### ISSUE TITLE
Please add the function of moving bookmarks up and down.

### ISSUE THREAD

**Issue by shui288** [kiwibrowser/android#106]
Kiwi-20190912203751:
Managing bookmarks for bookmarks cannot move positions up and down.
The Yandex browser bookmarks can be moved up and down. Please add the function of moving bookmarks up and down.

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
