### ISSUE TITLE
Privacy-friendly user agent

### ISSUE THREAD

**Issue by Madis0** [kiwibrowser/android#11]
In my opinion, Kiwi should use a more privacy-friendly user agent.

By that I mean: 

- no mention of Kiwi (!)
- stable Chrome version (even though Kiwi is newer) 
- less/no/common device info 

For comparison, here's my user agent on Kiwi Quenepa: 
```
Mozilla/5.0 (Linux; Android 8.1.0; ONEPLUS A5010 Build/OPM4.171019.021.R1) AppleWebKit/537.36 (KHTML, like Gecko) Kiwi Chrome/69.0.3440.40 Mobile Safari/537.36
```
Compare that with Bromite 68.0.3440.90:

```
Mozilla/5.0 (Linux; Android 8.1.0; SM-G965U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36
```
Firefox 63.0a1 contains even less info (but is notably not based on WebKit):
```
Mozilla/5.0 (Android 8.1.0; Mobile; rv:63.0) Gecko/63.0 Firefox/63.0
```

If you're (anyone reading this) curious about what these really contain, [use this UA parser](http://www.whatsmyua.info) for a readable output. 

_I also suggested this in XDA Forums, but posting here to keep better track of it._

**Comment by Djole01** [comment]
Luckily the kiwi browser offers support for extensions that can spoof user agents.
I'm using CyDec platform anti-fingerprint.
