### ISSUE TITLE
CHROMIUM missing gpu features 

### ISSUE THREAD

**Issue by LifeIsStrange** [kiwibrowser/android#115]
I don't know how you did manage to do that.
But:
Chrome 77 - >
![Screenshot_20191016_011126_com android chrome](https://user-images.githubusercontent.com/12934716/66876397-f169bf80-efb1-11e9-9136-8237e6511e1e.jpg)

Kiwi 77 - >
![Screenshot_20191016_011229_com kiwibrowser browser](https://user-images.githubusercontent.com/12934716/66876421-0fcfbb00-efb2-11e9-9ed4-b02ad8f06a82.jpg)

Could you fixe the discrepancies? It probably negatively affect rendering performance and battery usage.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
