### ISSUE TITLE
Update kiwi to chromium 78

### ISSUE THREAD

**Issue by LifeIsStrange** [kiwibrowser/android#116]
Chrome 78 will release in less than four days. 
The 22 october.
https://www.chromestatus.com/features/schedule

**Comment by LifeIsStrange** [comment]
@hjyoung1

**Comment by LifeIsStrange** [comment]
@Arnaud

**Comment by LifeIsStrange** [comment]
@Kiwi Browser

**Comment by arnaud** [comment]
wrong recipient

**Comment by Kiwi** [comment]
> wrong recipient

lol, same. Apparently I have been updated as afaict the title is the only place "I" was mentioned.

> You’re receiving notifications because you were mentioned.

**Comment by LifeIsStrange** [comment]
Sorry for the name mismatches ^^
Still you might be interested by what kiwi is:
It's the only Android browser to supports Chrome desktop extensions e.g uBlock Origin, YouTube background audio, etc

**Comment by darknodi** [comment]
@Kiwi you are the future. For Android Software Foundation.

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
