### ISSUE TITLE
Always Desktop not Working on Some Websites

### ISSUE THREAD

**Issue by vcheckzen** [kiwibrowser/android#117]
For example, this one:
https://www.bilibili.com/video/av73294947
Kiwi may failed to switch desktop ua before the ua recognition code executing on the head of that page.

**Comment by leafinote** [comment]
It seems some website (include bilibili.com) is also using "window.orientation" or/and "screen.orientation" in their JavaScript to detect mobile device.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
