### ISSUE TITLE
Built in adblocker false positive

### ISSUE THREAD

**Issue by nobelharvards** [kiwibrowser/android#119]
https://www.androidauthority.com/red-magic-3s-review-1045192/

<details>
<summary>What the page looks like with built in adblocker on:</summary>

![image](https://user-images.githubusercontent.com/9457934/68110231-9be55a80-ff40-11e9-97c4-031149471e97.png)
</details>

<details>
<summary>What the page looks like with it off/what it should look like:</summary>

![image](https://user-images.githubusercontent.com/9457934/68110262-af90c100-ff40-11e9-9a07-9b88aa78715f.png)
</details>

The built in adblocker blocks the entire page apart from the headers. All that's left is just a blank page.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
