### ISSUE TITLE
Regression - audio player controls work in phone but not TV box

### ISSUE THREAD

**Issue by xRadio-us** [kiwibrowser/android#120]
One of my web sites features a one-click-to-play radio jukebox with single category mini jukeboxes available. -- https://1-dot.com/radio -- https://1-dot.com/radio/newsplus -- etc.

Using Kiwi, the web page works well with Android smartphones and until recently it worked well on my Mecool BB2 Pro Amlogic S912-based Android TV box ... but not now.

Brave is my go-to Android web browser. However, Kiwi has Chrome extension options which makes Kiwi a lot more useful with extensions like Dark Reader and (yokris) Reader View.

On my TV box (Android 6.0.1), Kiwi 77 (October 2019) does not display the normal play/pause/etc audio controls in either Desktop Mode or Mobile Mode. Kiwi is the ONLY Android browser that I have tested on this TV box that fails to show these audio controls.

This is a Kiwi regression because these audio controls had been tested on more than a dozen Android browsers long ago as well as on Windows, Linux and iOS browsers.

Do note, that the audio controls work fine with the Kiwi browser on smartphones.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
