### ISSUE TITLE
Development still on-going?

### ISSUE THREAD

**Issue by ghost** [kiwibrowser/android#121]
Hi is development on this browser still on-going?

**Comment by d3ward** [comment]
Hi @githubsucks-usegitlab, yes development is still active. The repo is just not updated, there are no build since October, dev is working on a new build based on latest Chromium 78, he just need time to finish the build.

**Comment by LifeIsStrange** [comment]
@d3ward any update?

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
