### ISSUE TITLE
Open aliexpress, amazon, ebay, etc... links, in app instead webpage

### ISSUE THREAD

**Issue by eraser-head** [kiwibrowser/android#122]
Hi all. assuming you have a link from aliexpress, amazon, ebay ... kiwi allows you to open the link in the app instead of in the browser? How should I configure it? Thank you

**Comment by d3ward** [comment]
Hello @eraser-head,
Check Settings -> Accessibility, there is an option to enable open links in external apps

**Comment by eraser-head** [comment]
I can't find this option, i'm using miui 11 

![photo_2019-11-27_16-53-59](https://user-images.githubusercontent.com/17121702/69738516-88d83b80-1136-11ea-8ae9-a035b806b843.jpg)

by the way, thanks for the help in telegram, i'm the same guy :)

**Comment by eraser-head** [comment]
ohhhhh, in web browser!!!! I don't know how I haven't seen it before!!! it's working men, thanks a lot!!!! 🥇

**Comment by d3ward** [comment]
@eraser-head sorry, I thought you'd understand that I was talking about Kiwi, in the browser settings there's Accessibility section.
