### ISSUE TITLE
Array.flat method

### ISSUE THREAD

**Issue by laem** [kiwibrowser/android#123]
Hi, this javascript method seems to be missing, which is strange since chrome includes it since version 68.
Using polyfill.io doesn't resolve the issue.

**Comment by ponchofiesta** [comment]
Some changelog told about a 10% faster Javascript processing. Maybe Kiwi uses a different version of V8 than Chrome/Chromium does.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
