### ISSUE TITLE
(request feature) add fill link from clipboard

### ISSUE THREAD

**Issue by 3xploiton3** [kiwibrowser/android#124]
![](https://i.imgur.com/OxNd6LJ.jpg)
![](https://i.imgur.com/Y2abPLA.jpg)

As you can see, fill from clipboard is good way to paste web from any source

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
