### ISSUE TITLE
A bug of floccus extension

### ISSUE THREAD

**Issue by fxzxmicah** [kiwibrowser/android#125]
After using the floccus extension to synchronize bookmarks, according to the logs of floccus, the local synchronization has been successful, bookmarks already exist, but there is nothing in the browser bookmark page. But floccus works normally on PC, so is there a bug in Kiwi?

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
