### ISSUE TITLE
battery dry

### ISSUE THREAD

**Issue by sistema32** [kiwibrowser/android#128]
Hi, kiwi browser has a process running in the background that never stop and dry the battery.

**Comment by jdtechsol** [comment]
Broken English aside, of course it has a background process. With features like extensions (which includes background scripts, push notifications, etc), how would it work if it wasn't allowed to run in the background? Manually close the app if its "Drying" your battery.

**Comment by resynth1943** [comment]
"Drying" your battery is a new one for me. :stuck_out_tongue_closed_eyes:

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
