### ISSUE TITLE
Feature Request: Default Night Mode

### ISSUE THREAD

**Issue by xoihiox** [kiwibrowser/android#130]
You are killing it with this app.  It is miles better than anything available at the moment, and is the mobile browser I have been waiting for for years.  I had high hopes for the vivaldi team with their android browser, but they released a generic piece of garbage.  And kiwibrowser is managing to get just about everything right with what seems to be less time and what I imagine to be much less manpower.  Good job and keep it up.

My question:
I would like the night mode to be on almost 100% of the time.  Could you make that possible in a future update?

Please let me know if I am overlooking the option to enable that behavior presently.

Thank you.

**Comment by d3ward** [comment]
what you mean by "100% of the time"?

**Comment by xoihiox** [comment]
On my device, kiwi browser opens with night mode turned off by default.

I would like the option to have night mode turned on by default. I almost never turn it off. 

1. My eyes don't much like getting shocked whenever I open the app.
2. It is mildly tedious to activate night mode every time I open the app.

I hope that makes sense. Thanks!

**Comment by d3ward** [comment]
Ok. So if you have a tablet, unfortunately there is a bug with night mode. If your device is a smartphone then you shouldn't have that bug, try update to latest version. 
For tablet, you can try using dark reader extension as alternative/temporary fix.
