### ISSUE TITLE
"Kiwi failed during startup with an unexpected error" in Androidx86 VM

### ISSUE THREAD

**Issue by markpatx** [kiwibrowser/android#132]
I am trying to run Kiwi Browser in an Androidx86 virtualbox vm, in which both Chrome and Chromium work.

I got the kiwi apk from google play, and installed it using `adb install file.apk`, it installs correctly, but when I try to start it I get the error: "Kiwi failed during startup with an unexpected error", and it closes.

This is what I see on `adb logcat` at the moment of the crash:´

https://i.gyazo.com/b317f08135ac37eb2d65fa06cdd198fd.png

> 01-06 17:26:05.450  1144  3483 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.kiwibrowser.browser/com.google.android.apps.chrome.Main bnds=[678,189][844,302]} from uid 10022
> 01-06 17:26:05.459  1028  3355 I audio_hw_primary: choose pcmC0D0p for 0
> 01-06 17:26:05.467  1144  3483 I ActivityManager: Start proc 3522:com.kiwibrowser.browser/u0a72 for activity com.kiwibrowser.browser/com.google.android.apps.chrome.Main
> 01-06 17:26:05.469  3522  3522 I main    : type=1400 audit(0.0:475): avc: denied { mounton } for path="/storage" dev="tmpfs" ino=4261 scontext=u:r:zygote:s0 tcontext=u:object_r:tmpfs:s0 tclass=dir permissive=1
> 01-06 17:26:05.472  3522  3522 W nativebridge: Failed to bind-mount /system/lib/arm/cpuinfo as /proc/cpuinfo:No such file or directory
> 01-06 17:26:05.473  3522  3522 W libnb   : Native bridge is disabled
> 01-06 17:26:05.474  3522  3522 W zygote  : Unexpected CPU variant for X86 using defaults: x86_64
> 01-06 17:26:05.511  1144  1144 I Binder:1144_1A: type=1400 audit(0.0:476): avc: denied { write } for name="timerslack_ns" dev="proc" ino=13328 scontext=u:r:system_server:s0 tcontext=u:r:priv_app:s0:c512,c768 tclass=filepermissive=1
> 01-06 17:26:05.534  1045  1114 D AudioFlinger: mixer(0xec0836c0) throttle end: throttle time(9)
> 01-06 17:26:05.534  3522  3522 I cr_InstantAppsHandler: Package manager handles intents on O+, not handling in Chrome
> 01-06 17:26:05.566  1144  3483 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x14002000 cmp=com.kiwibrowser.browser/org.chromium.chrome.browser.ChromeTabbedActivity bnds=[678,189][844,302] (has extras)} from uid 10072
> 01-06 17:26:05.586  1144  3477 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:05.649  3522  3522 I cr_base : Android Locale: en_US requires .pak files: [en-GB, en-US]
> 01-06 17:26:05.657  3522  3543 E cr_LibraryLoader: Unable to load library: chrome
> 01-06 17:26:05.716  3522  3544 D OpenGLRenderer: HWUI GL Pipeline
> 01-06 17:26:05.745  1040  1172 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:05.782  3522  3542 I cr_tabmodel: Starting to fetch tab list for tab_state0
> 01-06 17:26:05.782  3522  3542 I cr_tabmodel: State file does not exist.
> 01-06 17:26:05.782  3522  3542 I cr_tabmodel: Starting to fetch tab list for tab_state1
> 01-06 17:26:05.782  3522  3542 I cr_tabmodel: State file does not exist.
> 01-06 17:26:05.810  3522  3544 I com.kiwibrowser.browser: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
> 01-06 17:26:05.811  3522  3544 I OpenGLRenderer: Initialized EGL, version 1.4
> 01-06 17:26:05.811  3522  3544 D OpenGLRenderer: Swap behavior 1
> 01-06 17:26:05.955  3522  3542 I cr_tabmodel: Starting to fetch tab list for tab_state_browser_actions
> 01-06 17:26:05.955  3522  3542 I cr_tabmodel: State file does not exist.
> 01-06 17:26:06.120  3522  3538 I cr_base : Extracting resource /data/user/0/com.kiwibrowser.browser/app_chrome/paks/en-GB.pak@9e
> 01-06 17:26:06.357  3522  3538 I cr_base : Extracting resource /data/user/0/com.kiwibrowser.browser/app_chrome/paks/en-US.pak@9e
> 01-06 17:26:06.388  3522  3533 I zygote  : Background concurrent copying GC freed 6606(1279KB) AllocSpace objects, 4(80KB) LOS objects, 49% free, 1817KB/3MB, paused 1us total 435.782ms
> 01-06 17:26:06.563  1144  1154 I zygote64: Background concurrent copying GC freed 59708(2MB) AllocSpace objects, 14(600KB) LOS objects, 42% free, 9MB/16MB, paused 20us total 1.009s
> 01-06 17:26:06.703  1040  1215 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:06.704  3522  3544 D vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
> 01-06 17:26:06.704  3522  3544 D vndksupport: Loading /vendor/lib/hw/gralloc.default.so from current namespace instead of sphal namespace.
> 01-06 17:26:06.706  3522  3544 D vndksupport: Loading /vendor/lib/hw/gralloc.default.so from current namespace instead of sphal namespace.
> 01-06 17:26:06.716  1040  1040 D SurfaceFlinger: duplicate layer name: changing com.kiwibrowser.browser/org.chromium.chrome.browser.ChromeTabbedActivity to com.kiwibrowser.browser/org.chromium.chrome.browser.ChromeTabbedActivity#1
> 01-06 17:26:06.745  1040  1172 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:06.745  1040  1172 I chatty  : uid=0(root) Binder:1040_3 identical 1 line
> 01-06 17:26:06.745  1040  1172 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:06.747  3522  3522 I zygote  : Deoptimizing int lz.j(android.view.View) due to JIT inline cache
> 01-06 17:26:06.751  3522  3522 I Choreographer: Skipped 59 frames!  The application may be doing too much work on its main thread.
> 01-06 17:26:06.914  1040  1097 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:07.346  3522  3522 D ViewRootImpl[ChromeTabbedActivity]: updatePointerIcon called with position out of bounds
> 01-06 17:26:07.342  1040  1097 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:07.346  3522  3522 I Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
> 01-06 17:26:07.349  1144  1166 I ActivityManager: Displayed com.kiwibrowser.browser/org.chromium.chrome.browser.ChromeTabbedActivity: +1s765ms (total +1s892ms)
> 01-06 17:26:07.544  1040  1097 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:07.643  1040  1658 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:08.979  1028  3355 I audio_hw_primary: choose pcmC0D0p for 0
> 01-06 17:26:09.023  1040  1040 E SurfaceFlinger: [Sprite#0] rejecting buffer: bufWidth=22, bufHeight=28, front.active.{w=25, h=25}
> 01-06 17:26:09.054  1040  1172 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:09.059  3522  3522 I com.kiwibrowser.browser: System.exit called, status: -1
> 01-06 17:26:09.059  3522  3522 I AndroidRuntime: VM exiting with result code -1, cleanup skipped.
> 01-06 17:26:09.067  1144  1213 W InputDispatcher: channel 'bc2d927 com.kiwibrowser.browser/org.chromium.chrome.browser.ChromeTabbedActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> 01-06 17:26:09.067  1144  1213 E InputDispatcher: channel 'bc2d927 com.kiwibrowser.browser/org.chromium.chrome.browser.ChromeTabbedActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 01-06 17:26:07.761  3522  3522 I chatty  : uid=10072(com.kiwibrowser.browser) browser.browser identical 5 lines
> 01-06 17:26:07.838  3522  3522 D ViewRootImpl[ChromeTabbedActivity]: updatePointerIcon called with position out of bounds
> 01-06 17:26:09.069  1144  3135 I ActivityManager: Process com.kiwibrowser.browser (pid 3522) has died: fore TOP
> 01-06 17:26:09.069  1144  1161 W system_server: kill(-3522, 9) failed: No such process
> 01-06 17:26:09.069  1144  3483 I WindowManager: WIN DEATH: Window{74b5472 u0 com.kiwibrowser.browser/org.chromium.chrome.browser.ChromeTabbedActivity EXITING}
> 01-06 17:26:09.071  1144  3135 W ActivityManager: Force removing ActivityRecord{2c834e3 u0 com.kiwibrowser.browser/org.chromium.chrome.browser.ChromeTabbedActivity t66}: app died, no saved state
> 01-06 17:26:09.071  1025  1025 I Zygote  : Process 3522 exited cleanly (255)
> 01-06 17:26:09.104  1045  1114 D AudioFlinger: mixer(0xec0836c0) throttle end: throttle time(6)
> 01-06 17:26:09.105  1144  2738 I WindowManager: WIN DEATH: Window{bc2d927 u0 com.kiwibrowser.browser/org.chromium.chrome.browser.ChromeTabbedActivity}
> 01-06 17:26:09.105  1144  2738 W InputDispatcher: Attempted to unregister already unregistered input channel 'bc2d927 com.kiwibrowser.browser/org.chromium.chrome.browser.ChromeTabbedActivity (server)'
> 01-06 17:26:09.113  1144  1161 W system_server: kill(-3522, 9) failed: No such process
> 01-06 17:26:09.113  1144  1161 I system_server: Successfully killed process cgroup uid 10072 pid 3522 in 44ms
> 01-06 17:26:09.283  1040  1215 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:09.342  1144  1166 W ActivityManager: setHasOverlayUi called on unknown pid: 3522
> 01-06 17:26:09.283  1040  1215 I chatty  : uid=0(root) Binder:1040_4 identical 1 line
> 01-06 17:26:09.283  1040  1215 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:09.376  1040  1099 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:09.386  1040  1099 I chatty  : uid=0(root) Binder:1040_2 identical 1 line
> 01-06 17:26:09.444  1040  1099 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:09.762  1040  1658 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
> 01-06 17:26:09.877  1702  1810 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

What could be the issue?

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
