### ISSUE TITLE
Kiwi suspends other tabs when switching

### ISSUE THREAD

**Issue by gggirlgeek** [kiwibrowser/android#134]
Hello and thank you very much for Kiwi. It fills a much needed void in the community.

I'm on a Firestick 4k. When using Kiwi it often suspends other tabs when I switch away from them, even if I only have 3 tabs open. It also closes in the background when I switch apps. Brave browser doesn't seem to do this. I have to open quite a few apps before Brave will close in the background. 

Admittadly, the Firstick gets very slow with Brave running after a while. But Kiwi closes (or suspends tabs) within a couple of minutes. It also happens on my phone with fast/large RAM (LG V20, Oreo.) There are tabs that I like to leave open for reference and they are a pain to reload.

Kiwi seems to be the only browser that does this even on a fast phone. Can I change some flags, or is this a bug?

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
