### ISSUE TITLE
Don't just "accept" cookies

### ISSUE THREAD

**Issue by Madis0** [kiwibrowser/android#14]
Quoting the forum post:

> Automatically accepts lots of "Please this is GDPR, and cookie, and blablabla" messages. It is not perfect yet, as many websites have added GDPR messages lately.

This approach has a lot of problems:

- Non-private settings accepted by default
- May break websites (assuming it just hides the notices that require a prompt answer)
- As you say, it doesn't work with newer websites

What I would suggest doing instead:

- Block the tracking methods
Do it like a [content blocker](https://github.com/gorhill/uBlock) - just block whatever the tracking cookies may do (e.g. [EasyPrivacy](https://easylist.to/easylist/easyprivacy.txt)) and then maybe block the notices that can be safely removed (e.g. [Fanboy's Cookiemonster](https://www.fanboy.co.nz/fanboy-cookiemonster.txt)). So for the rest it would matter less what the user responds, as the tracking will be blocked either way.
- Reject the cookies by bundling the appropriate cookies with the browser
A less reliable way would be giving the user opted out cookies right away, but that needs a lot of manual work (getting the cookies in the first place) and probably additional code (handle any tokens or userid-s that they may use to keep certain user's preferences).

**Comment by superlex** [comment]
Yep, I agree.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
