### ISSUE TITLE
Apply dark mode according to system settings

### ISSUE THREAD

**Issue by disacrol** [kiwibrowser/android#144]
Any chance kiwi could automatically enable dark mode when system does so? I mean, follow Android global settings.

**Comment by leifalbor** [comment]
+1 from me

**Comment by imforumman** [comment]
Just coming to Kiwi (after Firefox has destroyed their add-on community with the move from fennec to fenix). Would love to see this auto-night-mode possibility. Keep up the great work! Thank you so much!

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
