### ISSUE TITLE
Implement a chrome-like copy link function

### ISSUE THREAD

**Issue by Darkshine0** [kiwibrowser/android#148]
It would be nice if kiwi had a chrome-like feature which by clicking in the address toolbar a dedicated copy button would appear just like in regular chrome.
I think it would be more comfortable to use instead of selecting the whole address and the copying it.

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
