### ISSUE TITLE
Suggestion for enhancements

### ISSUE THREAD

**Issue by ghost** [kiwibrowser/android#15]
Instead of inversing the colour, please add a **dark screen overlay** feature that acts as a **dark curtain** over webpages. Inversing colour is **not supported by many websites** and (so) also looks unpleasant a bit.

I have already emailed you about this issue, but I am again mentioning it here for your convenience to look up.

**Comment by projectextremum** [comment]
@ghost do you mean overlays like `red moon` or similar apps?

**Comment by KaKi87** [comment]
Please check out the Dark Reader browser extension.
