### ISSUE TITLE
Has kiwi's development stopped?

### ISSUE THREAD

**Issue by pitsi** [kiwibrowser/android#152]
As the title suggests, I would like to ask if kiwi's development has actually stopped.

Its last update was 5 months ago, on early October 2019, and its version is equivalent to chromium 77, which in turn is pretty out of date in terms of security and features. And the same thing is also discussed on kiwi's thread on xda...

I would like to keep it as my main browser, but I can't since there are sites that need the latest version of any browser in order to work, for security reasons.

**Comment by fredgolightly** [comment]
Exactly. Please just announce you've moved on to other projects and close this one on xda/reddit/discord

**Comment by pitsi** [comment]
Since kiwi's code is now open, and because it has moved at another place, I hope there will be a new version soon and I will close this issue once it gets released to the store.

**Comment by pitsi** [comment]
Since there are some releases since last week, here
https://github.com/kiwibrowser/src/releases

I am closing this issue. I hope kiwi's package on the store will be updated soon, so as to reinstall it.

**Comment by fredgolightly** [comment]
These are just automatic builds, I've looked on discord and nothing is going to be released especially on the play for a long time if not even
