### ISSUE TITLE
'Enable NTP Button' flag not functional

### ISSUE THREAD

**Issue by minotalen** [kiwibrowser/android#16]
I tried to enable the functionality by going through flags, restarted my browser to no avail. Was hoping for a new tab button to the right of my tab counter.
'Force Enable Home Page Button' worked fine, displays a sleek homebutton to the left of the adress box.

**Comment by minotalen** [comment]
Wow, great! How did you find out?

**Comment by Madis0** [comment]
Was requested on XDA a while ago.
