### ISSUE TITLE
External links with YouTube & reddit not working 

### ISSUE THREAD

**Issue by Bradford1040** [kiwibrowser/android#161]
I have been banging my head against the wall trying anyway to fix this issue before posting here, when I search in kiwi browser and some results, not all, that have certain YouTube or reddit links (edit, keep in mind I have tried resetting permissions, even done a full fresh install of android 10,one UI 2.0 on a Samsung A50) I have to (with YouTube) either share to a custom shared link created with Tasker or let the browser version of YouTube open, click on the three dot YouTube menu and select desktop. Not the kiwi desktop browser mind you, tried that to and that is a dead end. Either of those ways it will open links in external app. (reddit) is a little easier, I long click on the link and open with external app, reddit app launches fine then, but if just clicked it will not recognize the app is even installed. Apologize for such a long post, but it's the short version of all I have done trying to find a workaround.

Second edit, I started with using playstore version and now using 64bit version 77.0.3865.116

Third edit: I ended up switching to desktop mode all the time, and use and app called "open link with" as it seems this is kiwi browser is not going to get an update or work in the foreseeable future. I am one big fan of the browser, wish it was still active.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
