### ISSUE TITLE
Error message when trying to enter full screen on videos

### ISSUE THREAD

**Issue by chostarman** [kiwibrowser/android#162]
If I try and watch a video, it loads, and plays.

However, whenever I press the full screen button, I get the chrome "awww snap" message.

![Screenshot_20200709_095451_com kiwibrowser browser](https://user-images.githubusercontent.com/27223368/87020216-7396b580-c1cb-11ea-8913-7b8b07805ff7.jpg)
![Screenshot_20200709_095502_com kiwibrowser browser](https://user-images.githubusercontent.com/27223368/87020229-772a3c80-c1cb-11ea-81ca-caf25d57e74a.jpg)

Screenshots are attached

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
