### ISSUE TITLE
Pasting from clipboard uses old clipboard data

### ISSUE THREAD

**Issue by besweeet** [kiwibrowser/android#166]
It seems like Kiwi doesn't stay in-sync with the latest clipboard data. For example,  Kiwi will paste something i copied from hours ago instead of something I copied just now. It's been doing this for a long time.

**Comment by bam2000** [comment]
same problem, also with Microsoft Edge Browser.
Very strange behavour, cannot paste from my password safe into websites password fields... very annoying and unusable...

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
