### ISSUE TITLE
kutt.it could not create short link #bug #crashes #hugebug

### ISSUE THREAD

**Issue by NEWBIENOOB-0** [kiwibrowser/android#167]
![Screenshot_2020-10-02-10-11-17-06_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/54370549/94889470-f0b78b00-0499-11eb-815b-d4287d72bbb7.jpg)
Kutt.It could not create
Short link
#bugs #bug #updates #updates64bits #hugebug https://kutt.it

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
