### ISSUE TITLE
Is there a way to disable mousewhell volume change on some video page?

### ISSUE THREAD

**Issue by 921j** [kiwibrowser/android#172]
I'm using kiwi brownser on a android VirtualBox，It's bothering me!

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).

**Comment by 921j** [comment]
> Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).

I'll try it,thx!
