### ISSUE TITLE
The UserAgent obtained from JavaScript object navigator.userAgent incorrect

### ISSUE THREAD

**Issue by Apollo2nd** [kiwibrowser/android#179]
1. 
Set browser prefer desktop mode, open a hyperlink in new tab, html look like:
`<a href=”checkagent.html” target="_blank">example</a>`

2. 
Check UserAgent in checkagent.html with JavaScript navigator.userAgent will get result :
`Mozilla/5.0 (Linux; Android 10; SCM-W09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.110 Safari/537.36`

This UserAgent string is mobile version but not desktop version.

3.
Some website check UserAgent locally and result in page displayed as mobile version.This bug make tablet devices have a not so good experience. Hope someone fix it soon, great thanks.

PS. When the hyperlink is opened in same tab, the UserAgent string still be desktop version. So this bug only represented click on hyperlink with "target=_blank"

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
