### ISSUE TITLE
Http 400 error trying to load chrome plugin page

### ISSUE THREAD

**Issue by ballo** [kiwibrowser/android#181]
For some reason I can't install plugins anymore. When I try to load a page like:
https://chrome.google.com/webstore/detail/honey/bmnlcjabgnpnenekpadlanbbkooimhnj?hl=en-US
I get:

400. That’s an error.

Your client has issued a malformed or illegal request. That’s all we know.

I can load it in incognito mode but can't install plugins from that mode. Disabling all extensions doesn't help. Resetting browser doesn't help.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
