### ISSUE TITLE
KiwiBrowser Android Aw Snap! Error

### ISSUE THREAD

**Issue by Havanur888** [kiwibrowser/android#182]
In the latest version of the kiwi browser, I get this error when watching videos or browsing pages on Twitch , Twitter. "Aw Snap!" page. but when I downloaded the old version (December 18-2020) there is no problem. my device: Xiaomi Note 3 (arm64v8a)

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
