### ISSUE TITLE
Charts and other infographics on bloomberg say "loading" on 

### ISSUE THREAD

**Issue by cloud9ineteen** [kiwibrowser/android#183]
Page works great on other browsers (chrome, edge, Firefox) on Android 11. Phone is pixel 3a.

https://www.bloomberg.com/graphics/covid-vaccine-tracker-global-distribution/

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
