### ISSUE TITLE
Missing support for Array.prototype.flatMap?

### ISSUE THREAD

**Issue by dot-sent** [kiwibrowser/android#184]
I've discovered recently that a browser game https://www.fallenlondon.com/ doesn't load properly in Kiwi. Specifically, the login/register page loads fine, but after authentication I get an error message after several seconds of loading. Technical/version details:

* Device: Samsung Galaxy S7
* Android version: 8.0.0
* Browser version: Kiwi browser, v. Git210216Gen570536402 (I literally copied this from browser's settings)

I've reported this issue to the game developers and got the following reply (shortened to technical part):

> I've narrowed this crash down to the fact that Kiwi doesn't support Array.prototype.flatMap, despite notionally built off Chromium 88 (at least in the latest version) — this means that we can't dynamically polyfill support via polyfill.io since Kiwi is claiming to be a recent enough browser to support it.
> 
> So I'm not sure what to recommend next — the best thing to do might be to contact the Kiwi maintainers themselves about this. The following line of JavaScript ought to return [1, 2, 3, 4, 5] but throws a TypeError in Kiwi:
> 
> [1, 2, [3, 4], 5].flatMap(_ => _)
>

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).

**Comment by dot-sent** [comment]
I confirm that the issue is not reproducible using the latest version from the Play Store.
