### ISSUE TITLE
93.0.4577.7 BUG,Click response position is not correct.

### ISSUE THREAD

**Issue by Sirius0060** [kiwibrowser/android#186]
https://imgtu.com/i/WsGec6
GIF demo

**Comment by KaKi87** [comment]
Are you experiencing this issue only on Kiwi Browser ?
Can you share the website's link ?
If you have answers, please re-post your issue at [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).

**Comment by Sirius0060** [comment]
> Are you experiencing this issue only on Kiwi Browser ?
> Can you share the website's link ?
> If you have answers, please re-post your issue at [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).

Yes, I am still using yandex Browser at the same time.
yandex Browser does not have this problem.
www.ithome.com/0/564/779.htm demo site
After testing multiple sites and scripts, the bottom position in the gif does not respond correctly.
