### ISSUE TITLE
2 bugs still in 93.0.4577.11

### ISSUE THREAD

**Issue by rick999999** [kiwibrowser/android#187]
#1 even i've checked the always desktop mode, it still keeps jumping back to mobile mode time by time
#2 i cant open any link in the bookmark, i have to long touch the link and choose to open it in new tab
there were no such bugs in any git2001915 version and before
i tested two devices and they have the same bugs
android os: 6.0 and 8.0

thx in advance!

**Comment by d3ward** [comment]
Please consider open a new issue on [src.next](https://github.com/kiwibrowser/src.next)
And 1 issue per problem is better 
When you create an issue and you add description remember that using "#" will trigger a link to another issue , so this can confuse everything
