### ISSUE TITLE
Accelerated or no animation?

### ISSUE THREAD

**Issue by CaesarW** [kiwibrowser/android#19]
Dear developer!  
The app is very fantastic and I've been using it for a while. But there's still a small issue.

The app is based on chromium, so we should see a lot in common with chromium. For me, the biggest difference is the disappearance of animations in app.

Are animations removed on purpose? Or is there any options to turn that on? I've looked that up in chrome://flags but no results.

Thanks in advance!

**Comment by thanuj10** [comment]
The animations are there to make the browser feel more faster. 
There is no option to enable the animations right now.

**Comment by CaesarW** [comment]
Will there be future update for this?
