### ISSUE TITLE
Some extensions not working on recent update.

### ISSUE THREAD

**Issue by Digital-XxX** [kiwibrowser/android#193]
[Cookie Editor](https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm/related) works in the past versions of Kiwi Browser but now, it doesn't.

Opening the extension show no options.

**Comment by KaKi87** [comment]
I cannot reproduce this issue on the latest Kiwi Browser version from the Play Store, please post further issues on [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
