### ISSUE TITLE
Can't authorize on Mastodon

### ISSUE THREAD

**Issue by derei** [kiwibrowser/android#194]
Trying to authorize a new login on Mastodon is impossible. The tab opens, but tapping on the button doesn't seem to do anything. Is like the request is being blocked by the browser.
I had to install another browser (duckduckgo) in order to be able to authorize.
Maybe it is worth looking into what is going on.

I'm running Ninja Cookie extension on kiwi, and I already tried to authorize with the extension disabled. No change.

**Comment by KaKi87** [comment]
I suppose you're talking about OAuth on Kiwi from the Tusky app.
I reproduced this issue a few days ago, but I am no longer reproducing it today.
Please post further issues on [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
