### ISSUE TITLE
[Suggestion] Alternative search engines

### ISSUE THREAD

**Issue by najodleglejszy** [kiwibrowser/android#2]
As far as I can tell, the only search engine available right now is Google. It would be great to see some additional search engines to choose from, like Qwant, DuckDuckGo, Searx.me, StartPage, Bing, Yahoo and so on. Most Chromium-based browsers I've tried provide a number of alternatives.

**Comment by Micky007** [comment]
![screenshot_20180713-175524](https://user-images.githubusercontent.com/11523796/42701268-649db390-86c6-11e8-8de4-d36cc54e3375.png)
That's it.

**Comment by Micky007** [comment]
In fact the "Add it to chrome" dialog showed on duckduckgo main page is for dekstop chrome builds, you obviously use android builds on your smartphone. Please read the blue text in the screenshot I've sent you because if you did you would have added succesfully duckduck search engine.

**Comment by RuthlessRuler** [comment]
yes, i tried again, It works for android Oreo devices but on a Jely Bean device it didnt work. So please fix the issue.

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
