### ISSUE TITLE
Miscellaneous suggestions

### ISSUE THREAD

**Issue by gdgsdg123** [kiwibrowser/android#21]
Miscellaneous suggestions, towards the most advanced browser in universe.

Originally posted on [XDA](https://forum.xda-developers.com/android/apps-games/app-kiwi-browser-chromium-adblock-caf-t3797252), but got removed [somehow](https://user-images.githubusercontent.com/33557593/48956941-51c7bc80-ef1b-11e8-9572-86d7c3759f23.png) :(
<img src="https://user-images.githubusercontent.com/33557593/48956941-51c7bc80-ef1b-11e8-9572-86d7c3759f23.png" width="90" height="160"/>
(perhaps due to blocked all ads from XDA or what...)
<br/>
<br/>
>- [x] 0
>Fixed in: Genie, 114<br/>
>Mitigation in: Kappa, 61
>Redesigned UI.
>
>[This](https://user-images.githubusercontent.com/33557593/48956503-ea107200-ef18-11e8-88e9-87e7fafb2f90.png) part(high-lighted), somehow appears too [**_obstructive_**](https://user-images.githubusercontent.com/33557593/48956518-f72d6100-ef18-11e8-9458-704cbd36994b.png):
>(while most users don't care about the **_statistics_**... option to **_toggle_** switch perhaps?)
><img src="https://user-images.githubusercontent.com/33557593/48956503-ea107200-ef18-11e8-88e9-87e7fafb2f90.png" width="90" height="160"/> <img src="https://user-images.githubusercontent.com/33557593/48956518-f72d6100-ef18-11e8-9458-704cbd36994b.png" width="90" height="160"/>

>- [ ] 1
>
>An option to switch **_off_** the [**_auto zoom-in_**](https://user-images.githubusercontent.com/33557593/48956870-f39ad980-ef1a-11e8-9354-c204473ba6ec.png)?
><img src="https://user-images.githubusercontent.com/33557593/48956870-f39ad980-ef1a-11e8-9354-c204473ba6ec.png" width="90" height="160"/>

>- [ ] 2
>
>**_Interactive_** [**_scroll-bar_**](https://user-images.githubusercontent.com/33557593/48956871-f695ca00-ef1a-11e8-853b-66be2afab89a.png)? (drag for fast navigation)
><img src="https://user-images.githubusercontent.com/33557593/48956871-f695ca00-ef1a-11e8-853b-66be2afab89a.png" width="90" height="160"/>

>- [ ] 3
>
>~~**_Omnibox_**(address-bar) **_auto hide_** toggle switch?~~
>("Settings" -> "Accessibility" -> "Toolbar always on screen", from: Quadea, 158)
>
>And an [optimization](https://user-images.githubusercontent.com/33557593/54008041-6d517e80-412a-11e9-879b-923fa24d1a37.png)/[extension](https://user-images.githubusercontent.com/33557593/54008047-75112300-412a-11e9-8ed4-d0d24d8cacf8.png) to Omnibox gestures:
><img src="https://user-images.githubusercontent.com/33557593/54008041-6d517e80-412a-11e9-879b-923fa24d1a37.png" width="90" height="160"/> <img src="https://user-images.githubusercontent.com/33557593/54008047-75112300-412a-11e9-8ed4-d0d24d8cacf8.png" width="90" height="160"/>

>- [ ] 4
>Mitigation in: Quadea, 158
>Via: "Settings" -> "Accessibility" -> "Desktop mode by default"
>
>**_Persistent_** **_"Desktop site"_** switch?
>(only applies on newly created tabs, doesn't change existed tabs)

>- [ ] 5
>
>**_Full URLs_** in [**_"History"_**](https://user-images.githubusercontent.com/33557593/48956874-fa295100-ef1a-11e8-9713-693a94159ff1.png)?.. (and **_"Bookmarks"_**)
><img src="https://user-images.githubusercontent.com/33557593/48956874-fa295100-ef1a-11e8-9713-693a94159ff1.png" width="90" height="160"/>

>- [ ] 6
>
>[Hmm...](https://user-images.githubusercontent.com/33557593/48956875-fd244180-ef1a-11e8-8948-4454517b452e.png) (edge of the page already)
>(**_"Find in page"_**, **_accessibility_**)
><img src="https://user-images.githubusercontent.com/33557593/48956875-fd244180-ef1a-11e8-8948-4454517b452e.png" width="90" height="160"/>
>
>Proposed solution:
>Making it retractable?.. (by sliding left/right on the right edge of the screen to show/hide)

>- [ ] 7
>Essentially a problem about the selection?..
>
>[This](https://user-images.githubusercontent.com/33557593/48956877-001f3200-ef1b-11e8-915d-8639217c636c.png) **_toolbox_**... somehow **_shows_** up even **_not active_** on any **_input_** element.
><img src="https://user-images.githubusercontent.com/33557593/48956877-001f3200-ef1b-11e8-915d-8639217c636c.png" width="90" height="160"/>

>- [ ] 8
>
>And [this](https://user-images.githubusercontent.com/33557593/48956883-0ad9c700-ef1b-11e8-842c-076d72a2bec5.png) is what happens when **_long-tap_** on **_empty area_** of some **_input_** element...
>(only "Paste"?.. Prefer "Ctrl + A" anyway.)
><img src="https://user-images.githubusercontent.com/33557593/48956883-0ad9c700-ef1b-11e8-842c-076d72a2bec5.png" width="90" height="160"/>

>- [x] 9
>Fixed in: Eta, 55
>Doesn't appear to occur since aforementioned version.
>(Verified in: Omicron, 69)
>
>**_Browsing_** while leaving **_pages_** with **_textbox_** with contents in ([this](https://user-images.githubusercontent.com/33557593/48956887-0f9e7b00-ef1b-11e8-9799-17137177ce43.png) one, eg) **_background_**.
><img src="https://user-images.githubusercontent.com/33557593/48956887-0f9e7b00-ef1b-11e8-9799-17137177ce43.png" width="90" height="160"/>
>When switch back, **_contents_** inside may **_disappear_**.

>- [ ] 10
>
>Something not right with [this](https://user-images.githubusercontent.com/33557593/48956889-13320200-ef1b-11e8-8af7-1f13e7d07214.png) thing...
>(**_Opened tabs_** (Incognito), **_"New incognito tab"_**)
><img src="https://user-images.githubusercontent.com/33557593/48956889-13320200-ef1b-11e8-8af7-1f13e7d07214.png" width="90" height="160"/> <img src="https://user-images.githubusercontent.com/33557593/48956894-16c58900-ef1b-11e8-9ada-39c758ade1ef.png" width="90" height="160"/>

>- [ ] 11
>
>[If any mistake...](https://user-images.githubusercontent.com/33557593/48956898-1a591000-ef1b-11e8-8abb-8c4d693429a5.png)
>(Notifications, **_"Close all incognito tabs"_**, **_Reconfirmation_**?..)
><img src="https://user-images.githubusercontent.com/33557593/48956898-1a591000-ef1b-11e8-8abb-8c4d693429a5.png" width="90" height="160"/>

>- [ ] 12
>
>Not fully [**_customizable_**](https://user-images.githubusercontent.com/33557593/48956902-1e852d80-ef1b-11e8-8353-b3e3769463c0.png)?..
>(**_"Download location"_**)
><img src="https://user-images.githubusercontent.com/33557593/48956902-1e852d80-ef1b-11e8-8353-b3e3769463c0.png" width="90" height="160"/>

>- [ ] 13
>
>And it... just [**_piles up_**](https://user-images.githubusercontent.com/33557593/48956905-2218b480-ef1b-11e8-8224-d36b7f607917.png), quite parallel.
>(**_Download Notifications_**)
><img src="https://user-images.githubusercontent.com/33557593/48956905-2218b480-ef1b-11e8-8224-d36b7f607917.png" width="90" height="160"/>

>- [ ] 14
>
>[**_"Copy link"_**](https://user-images.githubusercontent.com/33557593/48956906-25ac3b80-ef1b-11e8-9237-f5ffce88cadf.png)?.. as the situation got embarrassing [here](https://user-images.githubusercontent.com/33557593/48956908-29d85900-ef1b-11e8-9bf3-b9352e1b55ac.png)...
>(and show pop-up contains the copied text during call)
><img src="https://user-images.githubusercontent.com/33557593/48956906-25ac3b80-ef1b-11e8-9237-f5ffce88cadf.png" width="90" height="160"/> <img src="https://user-images.githubusercontent.com/33557593/48956908-29d85900-ef1b-11e8-9bf3-b9352e1b55ac.png" width="90" height="160"/>

>- [ ] 15
>
>**_"Open in new tab"_** context menu [here](https://user-images.githubusercontent.com/33557593/48956909-2d6be000-ef1b-11e8-90b6-928e77ad0241.png)?..
><img src="https://user-images.githubusercontent.com/33557593/48956909-2d6be000-ef1b-11e8-90b6-928e77ad0241.png" width="90" height="160"/>

>- [ ] 16
>
>Show **_navigation history_** [here](https://user-images.githubusercontent.com/33557593/48956913-30ff6700-ef1b-11e8-90f8-0889ed914c47.png) instead?.. (**_long press "Home"_**)
>(same as long press "Back" button)
><img src="https://user-images.githubusercontent.com/33557593/48956913-30ff6700-ef1b-11e8-90f8-0889ed914c47.png" width="90" height="160"/>

>- [ ] 17
>
>[**_"Opened tabs"_**](https://user-images.githubusercontent.com/33557593/48956915-3492ee00-ef1b-11e8-93ed-b92937ebe69a.png) button... Whoever **_long presses_** it may not want to open a tab, but close one...
>Make the long press to show a **_context menu_** perhaps?..
><img src="https://user-images.githubusercontent.com/33557593/48956915-3492ee00-ef1b-11e8-93ed-b92937ebe69a.png" width="90" height="160"/>

>- [ ] 18
>
>**_Reconfirmation_** on **_history_** entry [**_deletion_**](https://user-images.githubusercontent.com/33557593/48956923-3bb9fc00-ef1b-11e8-89f8-ee55ab467438.png)?..
><img src="https://user-images.githubusercontent.com/33557593/48956923-3bb9fc00-ef1b-11e8-89f8-ee55ab467438.png" width="90" height="160"/> <img src="https://user-images.githubusercontent.com/33557593/48956925-3f4d8300-ef1b-11e8-8d23-c68dd07d4456.png" width="90" height="160"/>

>- [ ] 19
>
>And in **_"History"_**, [here](https://user-images.githubusercontent.com/33557593/48956918-38267500-ef1b-11e8-888c-7d074fcca4db.png) press **_"Back" button_** will **_go back_** instead of hiding the toolbox.
>Whose behavior is inconsistent. (comparing to "Bookmarks", "Downloads")
><img src="https://user-images.githubusercontent.com/33557593/48956918-38267500-ef1b-11e8-888c-7d074fcca4db.png" width="90" height="160"/>

>- [x] 20
>Partly fixed in: Gamma, 49
>Behavior described in [this](https://user-images.githubusercontent.com/33557593/48956934-4b394500-ef1b-11e8-9905-c90f2c785a77.gif) is somewhat fixed?.. Still occurs at times.
>
>**_Omnibox_**(address-bar) with texts in, **_keyboard_**(arrow key left/right) **_behavior_**. (perhaps unwanted...)
><img src="https://user-images.githubusercontent.com/33557593/48956928-4379a080-ef1b-11e8-866e-8dd251724f29.gif" width="90" height="160"/> <img src="https://user-images.githubusercontent.com/33557593/48956931-470d2780-ef1b-11e8-87bd-ad843c78d454.gif" width="90" height="160"/> <img src="https://user-images.githubusercontent.com/33557593/48956934-4b394500-ef1b-11e8-9905-c90f2c785a77.gif" width="90" height="160"/>

>- [ ] 21
>
>[This](https://user-images.githubusercontent.com/33557593/48956938-4ecccc00-ef1b-11e8-81d0-2966b20a0620.png) thing **_unloads_** the current **_page_**... (causes refresh when go back)
>(**_"Recent tabs"_**)
><img src="https://user-images.githubusercontent.com/33557593/48956938-4ecccc00-ef1b-11e8-81d0-2966b20a0620.png" width="90" height="160"/>

>- [ ] 22
>
>An **_option_** to adjust **_UI font size_**?
>As one setting for all might [not work well](https://user-images.githubusercontent.com/33557593/48961804-2eae0480-ef3d-11e8-9ba7-047dc9afa4eb.png)...
><img src="https://user-images.githubusercontent.com/33557593/48961804-2eae0480-ef3d-11e8-9ba7-047dc9afa4eb.png" width="90" height="160"/>

>- [x] 23
>Fixed in: Andromeda, 93
>Via: "Settings" -> "Themes" -> "Ultra White"
>
>Option to force **_disable_** **_Omnibox_**(address-bar) **_coloring_**? (for whoever finds it somehow annoying...)

>- [x] 24
>Fixed in: Deneb, 102<br/>
>Partly fixed in: Gamma, 49
>Ineffective on start-up when set as: "chrome://newtab/"
>
>Which seems like an unintended behavior...
>
>[**_"Opened tabs"_**](https://user-images.githubusercontent.com/33557593/48956915-3492ee00-ef1b-11e8-93ed-b92937ebe69a.png) button (long press)
>"Opened tabs" -> [**_"New tab"_**](https://user-images.githubusercontent.com/33557593/49255759-93aca300-f3f2-11e8-8545-af17714f14c0.png)
><img src="https://user-images.githubusercontent.com/33557593/48956915-3492ee00-ef1b-11e8-93ed-b92937ebe69a.png" width="90" height="160"/> <img src="https://user-images.githubusercontent.com/33557593/49255759-93aca300-f3f2-11e8-8545-af17714f14c0.png" width="90" height="160"/>
>
>Opens default **_home page_** instead of custom home page defined at:
>"Settings" -> "Home page" -> ["Open this page"](https://user-images.githubusercontent.com/33557593/49255775-9c04de00-f3f2-11e8-8831-3618215c5de6.png)
><img src="https://user-images.githubusercontent.com/33557593/49255775-9c04de00-f3f2-11e8-8831-3618215c5de6.png" width="90" height="160"/>

>- [ ] 25
>
>**_Long-tap selecting_** on editable areas (eg, [textarea](https://user-images.githubusercontent.com/33557593/53294921-ced22e80-37b5-11e9-806a-99ff99d16c7d.png)), causes [**_extreme zooming_**](https://user-images.githubusercontent.com/33557593/53294925-db568700-37b5-11e9-80ba-cdb17d2d5f56.png).
><img src="https://user-images.githubusercontent.com/33557593/53294921-ced22e80-37b5-11e9-806a-99ff99d16c7d.png" width="90" height="160"/> <img src="https://user-images.githubusercontent.com/33557593/53294925-db568700-37b5-11e9-80ba-cdb17d2d5f56.png" width="90" height="160"/>

>- [ ] 26
>
>A function to **_generate_** the current **_URL to QR code_** image?..

>- [ ] 27
>
>Instead of going straight to **_"Select all"_** directly... try a similar [**_stepped selecting_**](https://user-images.githubusercontent.com/33557593/53688812-57e5ea00-3d0f-11e9-945b-01247769ef54.gif) schema perhaps?
>(word -> URI -> line -> container -> all)
><img src="https://user-images.githubusercontent.com/33557593/53688812-57e5ea00-3d0f-11e9-945b-01247769ef54.gif" width="90" height="160"/>

>- [ ] 28
>
>Functionality wise [these](https://user-images.githubusercontent.com/33557593/53690790-d7d37a80-3d36-11e9-8957-42c1e241fd93.png) 2 buttons are completely unnecessary... while they do take quite some space in this already crowded menu.
>
>Consider removing them? ~~(and I actually also want to mention that nameplate but... forget it for now)~~
><img src="https://user-images.githubusercontent.com/33557593/53690790-d7d37a80-3d36-11e9-8957-42c1e241fd93.png" width="90" height="160"/>

>- [ ] 29
>
>**_Realtime JavaScript control_** (without page refresh) from the [menu](https://user-images.githubusercontent.com/33557593/53690788-cee2a900-3d36-11e9-9872-7acf0e6245ab.png).
><img src="https://user-images.githubusercontent.com/33557593/53690788-cee2a900-3d36-11e9-9872-7acf0e6245ab.png" width="90" height="160"/>

>- [ ] 30
>
>**_"Tools"_** in the menu, offering **_built-in interface_** for easy access to some essential functions:
>encodeURIComponent()
>decodeURIComponent()
>atob()
>btoa()
>...
>(4 for now)
>
>And maybe a simple console shell?.. (in "Tools")

>- [ ] 31
>
>**_Advanced browsing parameter control_**:
>("Advanced options", access from a [button](https://user-images.githubusercontent.com/33557593/53690787-c7230480-3d36-11e9-9bbc-e47169ed6b39.png) aside Omnibox(address-bar), shows a page like "Settings" controlling below parameters)
>
>(URL)
>POST
>Referrer
>UA
>innerWidth
>Ignore redirections
>Reset contextmenu event
>Reset copy event
>Block clipboard access
>
>And these options can be **_integrated_** into saved entries in **_"Bookmarks"_**. (optional when "Advanced options" flag of the specific entry is set)
><img src="https://user-images.githubusercontent.com/33557593/53690787-c7230480-3d36-11e9-9bbc-e47169ed6b39.png" width="90" height="160"/>
>And when going back from a **_redirected_** page, **_prompt_** for **_"Ignore redirections"_** for smoother UX.

>- [ ] 32
>
>[Suggestion](https://user-images.githubusercontent.com/33557593/53690792-dbff9800-3d36-11e9-84d3-a9358309d07c.png) about an UI icon.
><img src="https://user-images.githubusercontent.com/33557593/53690792-dbff9800-3d36-11e9-84d3-a9358309d07c.png" width="90" height="160"/>

>- [ ] 33
>
>With the **_soft-keyboard_** on, **_sliding_** actions (tab switch/close) on [**_Omnibox_**](https://user-images.githubusercontent.com/33557593/53862912-7289be80-3fae-11e9-9fa5-c5849f59b105.png)(address-bar) are not being triggered.
><img src="https://user-images.githubusercontent.com/33557593/53862912-7289be80-3fae-11e9-9fa5-c5849f59b105.png" width="90" height="160"/>
>Also I find the maximum achievable tab switching speed being bottlenecked by the transition animation... (again an example of counter-user animation)

>- [ ] 34
>
>**_Navigation_** (via Omnibox) to "kiwi://extensions" triggers **_search_** engine...
>(probably for the whole **_"kiwi://"_** protocol... "chrome://" works OK)

>- [ ] 35
>
>First reported on XDA:
>https://forum.xda-developers.com/showpost.php?p=79601575
>https://forum.xda-developers.com/showpost.php?p=79602090
>
>**_"Back" button misbehavior_**... (causes the browser to go **_background_**... **_inopportunely_**)
>
>Affects all newly created tabs via below (might missed some) routines:
>"New tab";
>"New incognito tab";
>"Bookmarks" -> "Select" -> "Open in new tab";
>"Extensions";

**Comment by gdgsdg123** [comment]
BTW I'd like to provide translation support for the UI (English -> Chinese), send me a reference file I'll do the work.

**Comment by gdgsdg123** [comment]
And I use with following "labs_experiments", any comment?.. (what is unnecessary due to default already, etc)

>[PasswordForceSaving](chrome://flags#PasswordForceSaving)@1 ("Enabled")
>[autoplay-policy](chrome://flags#autoplay-policy)@3 ("Document user activation is required.")
>[clear-old-browsing-data](chrome://flags#clear-old-browsing-data)@2 ("Disabled")
>[disable-pull-to-refresh-effect](chrome://flags#disable-pull-to-refresh-effect)
>[disallow-unsafe-http-downloads](chrome://flags#disallow-unsafe-http-downloads)@2 ("Disabled")
>[dont-prefetch-libraries](chrome://flags#dont-prefetch-libraries)@1 ("Enabled")
>[enable-clipboard-provider](chrome://flags#enable-clipboard-provider)@2 ("Disabled")
>[enable-downloads-location-change](chrome://flags#enable-downloads-location-change)@1 ("Enabled")
>[enable-fast-unload](chrome://flags#enable-fast-unload)
>[enable-horizontal-tab-switcher](chrome://flags#enable-horizontal-tab-switcher)@1 ("Enabled")
>[enable-md-incognito-ntp](chrome://flags#enable-md-incognito-ntp)@2 ("Disabled")
>[enable-ntp-article-suggestions-expandable-header](chrome://flags#enable-ntp-article-suggestions-expandable-header)@1 ("Enabled")
>[enable-ntp-snippets-increased-visibility](chrome://flags#enable-ntp-snippets-increased-visibility)@1 ("Enabled")
>[enable-osk-overscroll](chrome://flags#enable-osk-overscroll)
>[enable-parallel-downloading](chrome://flags#enable-parallel-downloading)@1 ("Enabled")
>[enable-query-in-omnibox](chrome://flags#enable-query-in-omnibox)@2 ("Disabled")
>[enable-quic](chrome://flags#enable-quic)@1 ("Enabled")
>[enable-tcp-fast-open](chrome://flags#enable-tcp-fast-open)
>[expensive-background-timer-throttling](chrome://flags#expensive-background-timer-throttling)@1 ("Enabled")
>[long-press-back-for-history](chrome://flags#long-press-back-for-history)@2 ("Disabled")
>[offline-bookmarks](chrome://flags#offline-bookmarks)@1 ("Enabled")
>[offline-pages-failed-download](chrome://flags#offline-pages-failed-download)@1 ("Enabled")
>[offline-pages-pending-download](chrome://flags#offline-pages-pending-download)@1 ("Enabled")
>[omnibox-spare-renderer](chrome://flags#omnibox-spare-renderer)@2 ("Disabled")
>[omnibox-ui-hide-steady-state-url-scheme-and-subdomains](chrome://flags#omnibox-ui-hide-steady-state-url-scheme-and-subdomains)@2 ("Disabled")
>[simplified-ntp](chrome://flags#simplified-ntp)@1 ("Enabled")
>[smooth-scrolling](chrome://flags#smooth-scrolling)@2 ("Disabled")

**Comment by halcion** [comment]
Wow, very comprehensive list of things that certainly need fixing. Can we get a reply from the developer please?!

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store, post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues), and always create individual posts for each bug report or feature request.
