### ISSUE TITLE
Please upgrade to the latest Chromium stable or Canary base.

### ISSUE THREAD

**Issue by thanuj10** [kiwibrowser/android#23]
This browser has great features and an impressive adblock. But the browser is severely out-of-date in respect to the underlying code. 

Browser is based on Chromium 69 when latest Chrome is based off Chromium 71.

Please update to base chromium code to fix all te security issues and bugs the later chromium code fixed.

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
