### ISSUE TITLE
Give us advanced adblock controls

### ISSUE THREAD

**Issue by ghost** [kiwibrowser/android#24]
I'd like to be able to control which adblock lists Kiwi uses, add more blocklists and keep them updated manually.

**Comment by superlex** [comment]
Yep, I agree.
It could, at least, let you choose if enable
- generic adblock & tracking list
- social list
- annoyances list (see #14 )
- regional list

**Comment by KaKi87** [comment]
Please consider using an adblocker like uBlock Origin and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
