### ISSUE TITLE
disable top right bar animation

### ISSUE THREAD

**Issue by traktori** [kiwibrowser/android#25]
most of the chrome animation are absent in kiwi, such I think is a great positive... all but one - the animation of the top right 3-dotted menu still has an animation as it expands, which I think counters the overall design of the browser. thanks.

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
