### ISSUE TITLE
Discover news feed empty

### ISSUE THREAD

**Issue by hexagonius** [kiwibrowser/android#258]
Since about two weeks the discover news feed on the start page is not showing anything anymore. The white boxes of the first entry subtly flash for a short moment but that's it

**Comment by ppajda** [comment]
Same for me

**Comment by R411gun** [comment]
same, this bug exists over a month now

**Comment by hexagonius** [comment]
Is this browser still being worked on?

**Comment by hexagonius** [comment]
Works again
