### ISSUE TITLE
Add "Reopen closed tab" to tab menu.

### ISSUE THREAD

**Issue by Lululalu** [kiwibrowser/android#26]
![screenshot_20190209-173634_kiwi browser](https://user-images.githubusercontent.com/32398857/52525481-4aa28600-2ca2-11e9-9fef-97147bf7f003.jpg)

Opera mobile has this feature and I find it quite useful.

**Comment by NotesOfReality** [comment]
I don't get why this issue has been closed.
@Lululalu could you please explain it ?
