### ISSUE TITLE
Enable TLS 1.3 FINAL BY DEFAULT . 

### ISSUE THREAD

**Issue by Techguyprivate** [kiwibrowser/android#28]
TLS 1.3 Final is already released and is enabled on every major browsers .

**Comment by xonexx** [comment]
Yes. It's a standard feature now. Please update to latest chromium and add TLS 1.3 support

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
