### ISSUE TITLE
Kiwi browser makes LG unusable while playing video.

### ISSUE THREAD

**Issue by shmykelsa** [kiwibrowser/android#29]
I have installed Kiwi Browser on my LG V10 running Android 7.0

Every time I start a video on Kiwi Browser, an ANR dialog comes up saying "com.lge.urmp has stopped". A new ANR dialog comes up in a matter of half a second when dismissing the other one by tapping on "close app".
Closing the video makes the issue disappear. 

Closer inspection on a logcat: I think this issue is related to the second screen of the device, that every time a player plays a media, it switches to the "player screen", with controls. 

No other browser has this issue. Not even Chrome.

I'll attach the log here.

[logcat.txt](https://github.com/kiwibrowser/android/files/2866384/logcat.txt)

**Comment by thanuj10** [comment]
Try disabling the New Media Controls flag from chrome://flags

**Comment by shmykelsa** [comment]
That actually worked, so I'll take it as a temporary fix. Though I've spoken with arnaud on Discord and found out where the issue was (something going on with the icon)

**Comment by thanuj10** [comment]
Glad i could help you. Just don't forget to post in the bugs section on Discord.


Cheers.

**Comment by shmykelsa** [comment]
Yeah I've already done it. Anyway, seems like the problem is righ back again. Even with that flag disabled. It seems like it worked once. I don't really know. I'm in contact with the developer on Discord, so we'll see.
