### ISSUE TITLE
The ChromeStore can no longer be displayed

### ISSUE THREAD

**Issue by clemoun** [kiwibrowser/android#292]
**Bug :**
When trying to display the Chromestore extension pages on KiwiBrowser (ex with AdBlock : https://chromewebstore.google.com/detail/adblock-plus-bloqueur-de/cfhdojbkjhnklbpkdaibdccddilifddb)

KiwiBrowser displays a ERR_TOO_MANY_REDIRECTS error

**Consequences :**
Users are no longer able to install chrome extensions on Kiwi Browser

**Workaround : **
Note that enabling the "show desktop version" fixes the issue

This seems linked to several changes made by Google on the Chromestore lately (including visual changes)

**Comment by Githubmaniak** [comment]
When this problem arose, I had to use a method of pinning the Chrome Store to the desktop page.

**Comment by clemoun** [comment]
This seems to be working again.

:+1:
