### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by airon90** [kiwibrowser/android#30]
The browser is open source. So is it possible to add it in [F-Droid](https://f-droid.org) catalogue? [I opened](https://gitlab.com/fdroid/rfp/issues/906) a RfP

**Comment by Techguyprivate** [comment]
No. The browser is not fully open source like open in open source. It is a common myth and misconception about Kiwi Browser. If it will be on F-droid, then it will be good cause have to provide full source code about everything without hiding anything.

**Comment by Laicure** [comment]
Damn, 1 commit and nothing else but keeps updating and releasing apks? Looked into the issues and scarely seen replies.
I think this repo is just to show that "hey, I provided the so-called **source code** (even though not fully open-source as said above) so trust me and install me" thing.

**Comment by ivysrono** [comment]
+1

**Comment by NotesOfReality** [comment]
@Laicure same impression as yours

**Comment by Laicure** [comment]
@NotesOfReality, I was about to install the app because it looks promising and about to replace my Chrome on my android phone but nope.
Big nope for me because I browse the internet for everything, even banking. At least, Chrome is open-source though proprietary freeware.

I still need proofs or something if kiwi is a trusted browser.

**Comment by NotesOfReality** [comment]
@Laicure why don't you use Bromite then? 
It's maybe the major competitor of Kiwi

**Comment by Laicure** [comment]
> @Laicure why don't you use Bromite then?
> It's maybe the major competitor of Kiwi

Oh, I used it (works really great, I really love the adblocking that I can even ditch dns66 and the like) but I mainly depend on syncing things via my Google Account so... :(

**Comment by NotesOfReality** [comment]
> > @Laicure why don't you use Bromite then?
> > It's maybe the major competitor of Kiwi
> 
> Oh, I used it (works really great, I really love the adblocking that I can even ditch dns66 and the like) but I mainly depend on syncing things via my Google account so... :(

Damn, though it isn't the same, EverSync and Raindrop.io have their Android app too.

**Comment by Laicure** [comment]
a bit out-of-topic though hehe!

> > > @Laicure why don't you use Bromite then?
> > > It's maybe the major competitor of Kiwi
> > 
> > 
> > Oh, I used it (works really great, I really love the adblocking that I can even ditch dns66 and the like) but I mainly depend on syncing things via my Google account so... :(
> 
> Damn, though it isn't the same, EverSync and Raindrop.io have their Android app too.

oh cool suggestions!
/hmm I sync passwords, extensions, and bookmarks :(
and I don't want to have other company or 3rd party app to manage those :D
It's like _if I will give my info to someone, I let Google handle it instead of an unknown company (applies for passwords only)_.

I'm currently looking for ways to sync chrome bookmarks and/or passwords to an unrooted android phone, I am still willing to switch :D

**Comment by DJCrashdummy** [comment]
@Laicure why not use Firefox then? - i'm not sure if their sever is still FOSS, but i heard/read somewhere at least all data should be E2E-encrypted.

or (what i recommend - don't thrust anyone with your passwords!) use a real password safe like [KeePassXC](https://keepassxc.org/) which works x-platform & x-browser for your passwords (and sync the data with whatever untrustworthy cloud you want).
just to mention it: similar to that you can use [Floccus](https://github.com/marcelklehr/floccus) (which also works x-browser) to sync your bookmarks with any cloud service, but unfortunately [firefox on android still not supports it](https://github.com/marcelklehr/floccus/issues/3). :disappointed:

**Comment by Laicure** [comment]
> @Laicure why not use Firefox then? - i'm not sure if their sever is still FOSS, but i heard/read somewhere at least all data should be E2E-encrypted.
> 
> or (what i recommend - don't thrust anyone with your passwords!) use a real password safe like [KeePassXC](https://keepassxc.org/) which works x-platform & x-browser for your passwords (and sync the data with whatever untrustworthy cloud you want).
> _just to mention it: similar to that you can use [Floccus](https://github.com/marcelklehr/floccus) (which also works x-browser) to sync your bookmarks with any cloud service, but unfortunately [firefox on android still not supports it](https://github.com/marcelklehr/floccus/issues/3)._ 😞
> 
> sorry for also being clearly OT.

No worries, I use Firefox and also Bromite.
I am just concerned about this Kiwi thing. ;)

**Comment by dimqua** [comment]
Unlike Bromite, Kiwi has addons support.

**Comment by awsms** [comment]
@dimqua unlike kiwi, bromite is free software and respect your privacy ; while kiwi phones home and communicates with 4 cloudflare servers each time you launch the application (test it with wireshark, you will see)

**Comment by DontUseGithub** [comment]
up

**Comment by Laicure** [comment]
> up

this will never happen
the repo here is just a mere scam to say it is "open-source"
even the dev is not responding here, only through his Discord and through his xda for kiwi disciples, ugh

**Comment by airon90** [comment]
I close the issue and I suppose it would not be open again, stantibus rebus

**Comment by kiwibrowser** [comment]
Hi,

Thanks for your patience, there were lot of considerations before actually open-sourcing the project.
Fixed, now 100% open-source and development moved to public git (which becomes the main central repo) - https://github.com/kiwibrowser/src

Adding to F-Droid is theoretically possible now (it would take lot of time though!) :)

**Comment by DJCrashdummy** [comment]
jfi: https://github.com/kiwibrowser/src/issues/6

**Comment by NextDev65** [comment]
What happened?

**Comment by Laicure** [comment]
> jfi: https://github.com/kiwibrowser/src/issues/6

Issues tab disabled in kiwibrowser/src

A big nah~

**Comment by KaKi87** [comment]
Oops, I'll look into that now.

**Comment by KaKi87** [comment]
*kiwibrowser/src#6* was transferred to kiwibrowser/src.next#91, please continue discussing F-Droid there.
