### ISSUE TITLE
Date in home page shows 49years

### ISSUE THREAD

**Issue by abhinashpati** [kiwibrowser/android#31]
They news or article link in home page is showing date as 49 years. Please see the screenshot from the links for further information.it doesn't even after pressing the refresh button or pull to refresh button.

https://photos.app.goo.gl/58E22fpTnQHeNDG87

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
