### ISSUE TITLE
Tablet : dark mode unset on each launch

### ISSUE THREAD

**Issue by manuw2009** [kiwibrowser/android#32]

**Comment by manuw2009** [comment]
Using mipad 4, Xiaomi.eu, dark mode can be set just fine, but it is not remembered. Next time you launch the browser, it's gone

**Comment by manuw2009** [comment]
Tried on LineageOS 16 as well.
Not working either.
Could you please look into it ?
I would really like to set dark mode as permanent as on my phone.
(love the browser !)

**Comment by AdamKane41** [comment]
same issue on my acer tablet too... Tonigh i'll go check all of kiwi's 'activities' , maybe theres something there i dont know. Peace

**Comment by Sada-Mio** [comment]
I have this issue too on Fire HD10 & Tab S6 tablets

**Comment by AdamKane41** [comment]
#130
