### ISSUE TITLE
Add devtools

### ISSUE THREAD

**Issue by shirtjs** [kiwibrowser/android#37]
You guys managed to get chrome extensions working which is awesome! It would be awesome if you guys could get devtools working too!

**Comment by tophf** [comment]
Devtools is pretty much unusable on small screens which is why it's removed in all mobile browsers, also to reduce the size of the app. Everyone is using remote debugging instead. You can use it with Kiwi as well.

**Comment by shirtjs** [comment]
Alright, thanks! Didn't really think of it in the way that it's unusable! Thanks for your hard work!

**Comment by laem** [comment]
Do you think it would be possible to add the DevTools as an extension ? In order to not ship it in the base version but allow power users to install it. 

Samsung Dex, Huawei desktop mode, and soon Android Q desktop mode all allow using the browser connected to an external monitor.

**Comment by hltdev8642** [comment]
just find a dev tools extension, I can imagine without even googling it that there are literally hundreds of options out there!

**Comment by laem** [comment]
No there's not a single one :disappointed: :

**Comment by hltdev8642** [comment]
> No there's not a single one

I finally found one!  ...well someone on the discord chat did... 

[Try this out](https://chrome.google.com/webstore/detail/mobile-devtools/okfdckomkajiaeejefanbonnhppmplpo)

**Comment by laem** [comment]
That's really cool. I figured out you could launch Eruda pasting this in the URL : `javascript:(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();`. You can also set this page as a favorite to load the console. 
But with an extension it's even better.

However, Eruda is designed for mobile use. I'd still be interested to get full Chrome dev tools. 
I guess it would be possible to read this extensions's code to see how to package
 https://github.com/ChromeDevTools/devtools-frontend.
