### ISSUE TITLE
Extensions keep crashing randomly 

### ISSUE THREAD

**Issue by JosephTico** [kiwibrowser/android#38]
I'm having issues with extensions in Chrome. I curenly have:

- Nano Defender
- Nano Adblocker
- Pop up blocker
- Bitwarden
- Bypass Paywalls (installed via dev mode)

And randomly extensions appear to be crashing. When I visit the extensions page a blue "Reload" button appears.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
