### ISSUE TITLE
When is this "Extension supported" version will be release in Play Store. According to XDA article, its already 24+ and its should have been released by now.

### ISSUE THREAD

**Issue by PranavBhattari** [kiwibrowser/android#39]
OR is it a beta release?

**Comment by NotesOfReality** [comment]
LOL I _guess_ the version you wanted had been released.
May you please close this issue please?
I mean, ATM it's just occupying useless space in the opened issues list, don't you think so ?

**Comment by PranavBhattari** [comment]
@NotesOfReality  I other moderators will close this issue. They must be busy. I will close this now.
Thanks for reminding this.
