### ISSUE TITLE
Feature Request: The browser should separate "Night mode" effect. 

### ISSUE THREAD

**Issue by PranavBhattarai** [kiwibrowser/android#40]
Still, there are my issues using "Night mode" on many web-pages it doesn't support.  
We love when the app looks black. But we have turn Night mode ON/OFF time and again to see the image without being overridden. 

This is really annoying to on a daily basis. 

Please separate these two effects. **Don't merge** them into one.

P.S: Give the user the right to view the browser in Black without converting the webpages into the dark. Separate "Dark webpages" and "Dark Browser's theme".

**Comment by hjyoung1** [comment]
It's available in latest beta version.

**Comment by PranavBhattrai** [comment]
Wow, that's great. When is beta will be published as general update?

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
