### ISSUE TITLE
What is the chromium version? 

### ISSUE THREAD

**Issue by Techguyprivate** [kiwibrowser/android#41]
Can we know what is the chromium version of the latest version of the browser? 

Also , is the tls 1.3 final enabled by default ?

**Comment by tophf** [comment]
The version is shown in settings -> about. As for tls, try an online test like https://www.ssllabs.com/ssltest/viewMyClient.html - it shows 1.3 is enabled, but you can force it anyway in `chrome://flags`

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
