### ISSUE TITLE
Cannot open PDF within browser, refreshing crashes the app

### ISSUE THREAD

**Issue by cjones26** [kiwibrowser/android#42]
When attempting to access a PDF document in the latest Kiwi Browser on a Samsung Galaxy S8, I am not able to view the PDF, as I only receive a gray screen.  I have tried by with Settings->Accessibility->Enable External applicatons both enabled and disabled, though this makes no difference.

When I attempt to refresh the page on this gray screen, the app crashes.  I have submitted the logs as well.

**Comment by Josephvb10** [comment]
Same problem.

**Comment by berkan** [comment]
Same problem here too. 

Samsung Galaxy A3, Android 8.0

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
