### ISSUE TITLE
kiwi browser and ublock (feature broken)

### ISSUE THREAD

**Issue by xlollomanx** [kiwibrowser/android#45]
I don't know if it's browser or addon related, but in ublock origin the element picker don't work. Element picker let you choose any element in the page and remove it temporarily or permanently by clicking one of these two button (see this picture for better details: [https://prnt.sc/ndpvcy](https://prnt.sc/ndpvcy). I've tested this even on yandex mobile because it's support chrome addon as well and this feature is working. Adblocking on kiwi is working wonderfully btw.

edit: Seems like this is defenitely a browser issue by reading here: [https://github.com/uBlockOrigin/uBlock-issues/issues/529](https://github.com/uBlockOrigin/uBlock-issues/issues/529)

**Comment by tophf** [comment]
That's because Kiwi is opening the extension's popup in a tab. Most of extensions are broken since they query the active tab so instead of the original page they get their own popup now. I hope it's temporary and later it'll be implemented properly, like for example in Yandex browser on Android.

**Comment by superlex** [comment]
It works well now, element picker too :)

**Comment by xlollomanx** [comment]
yes, now with new update works fine. Should I close this, or wait for dev?

**Comment by hjyoung1** [comment]
If it's fixed then please close no need to wait for dev.

**Comment by superlex** [comment]
I've some troubles with user filter editor. Could you check, please? Thanks.

**Comment by xlollomanx** [comment]
@superlex you mean the editor that let u edit your filters? Yes, it have problem even on yandex, I don't know if this is addon or browser related. On firefox it works better. 
Now I have to report that sometimes the addon nano adblocker (ublock varaint) crash and I have to tap on reload in `chrome://extensions`

**Comment by superlex** [comment]
> you mean the editor that let u edit your filters?

Yep, I find very difficult editing a rule or deleting some of them..

**Comment by gggirlgeek** [comment]
How do you use element picker in Android? I am on Firestick with a usb mouse and ublock options open in a new tab like you said. Element picker doesn't react to me at all. Same on my Android 8 phone (but no mouse).

I would love to see a context menu option to block elements but that is a ublock request I guess.

Can someone help and maybe post a screenshot of what you did?
