### ISSUE TITLE
Extension ScriptSafe

### ISSUE THREAD

**Issue by Ranger2000** [kiwibrowser/android#47]
Thank you for the cool extension function.
Could you manage that the extension "ScriptSafe"will work. Because after adding it, kiwi always crash.

https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf?hl=de

Or it will be better to include the fingerprinting functions into kiwi.

**Comment by KaKi87** [comment]
Please try up to date extensions, check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
