### ISSUE TITLE
There are some problems and proposals in use. 

### ISSUE THREAD

**Issue by yubifeng** [kiwibrowser/android#49]
Although it is so excellent , but there are some problems  in use. For example, I add a extension called infinity pro , a newtab tool, but kiwi will open  the homepage of kiwi browser itself ,so I have to touch the homepage button to enter the newtab of infinity pro. Also, in kiwi, you will enter a new  big page but not  a small window in current page like  PC Chrome   if you touch the extensions you install，which makes    the operations of the extension of Extension manager , Tampermonkey  and so on  inconvenient. What is more， if possible，please add the  additional function of Scan QR code， because it is important in China. Finally， with the greatest respect to great developers of kiwi。

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store, post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues), and always create individual posts for each bug report or feature request.
