### ISSUE TITLE
Per-Site Settings

### ISSUE THREAD

**Issue by NotesOfReality** [kiwibrowser/android#5]
This feature is fully functional in Chromium SWE builds by scweeny , its browser is called "CS Browser" ( https://play.google.com/store/apps/details?id=net.scweeny.CS.browser.dev&hl=en) , here is its github  https://github.com/scweeny/CAF/tree/m60_s .
Here I attach its screenshot with my comments about ipothetical priority.
![inkedscreenshot_20180713-212656_li](https://user-images.githubusercontent.com/11523796/42712661-c013e994-86ec-11e8-9788-1e8e5e7e9835.jpg)
![inkedscreenshot_20180713-212718_li](https://user-images.githubusercontent.com/11523796/42712662-c0339546-86ec-11e8-8609-1191e73ded57.jpg)
![inkedscreenshot_20180713-212728_li](https://user-images.githubusercontent.com/11523796/42712663-c05327bc-86ec-11e8-9c16-5bb230932f0b.jpg)
![inkedscreenshot_20180713-212737_li](https://user-images.githubusercontent.com/11523796/42712664-c06e26fc-86ec-11e8-8bb5-29649d34d8ac.jpg)

**Comment by Micky007** [comment]
What I'm actually interested in isn't changing website permissions before any site asks for them , I'm interested in this kind of permission management. Other features are interesting too but less than that one.

**Comment by Madis0** [comment]
In your screenshot, there are lots of not needed stuff and they are so marked by you, too. The adblock is already prominent in permissions, security state is in page info popup, usage stats are in site settings already... So I still don't understand what you _really_ miss from SWE.

**Comment by Micky007** [comment]
I've just discovered that section of Kiwi ,excuse me for my dumbness , still I have some questions.
Could "Web Defender" and "XSS Defender" be useless in Kiwi Browser ?
Would "Privacy Meter" be a shitton of useless work to be implemented?

**Comment by Madis0** [comment]
> Could "Web Defender" and "XSS Defender" be useless in Kiwi Browser ?
No, but I would assume they are implemented already as adblock filters.
>Would "Privacy Meter" be a shitton of useless work to be implemented?
Yes. I never really understood what it counted as "privacy". If anything, it would be way more useful to have extension support so you could install your own "meters" at will.

**Comment by Micky007** [comment]
OK ,so thank you very much for the explanation, the help and the patience(considering my dumbness). Have a nice day. I guess this issue should be closed now.
