### ISSUE TITLE
How to call Headless browser via normal android service

### ISSUE THREAD

**Issue by beshoo** [kiwibrowser/android#50]
Dear All 
I have a big challenged and I love to share it with you.
I want to automate web scraping. via Android application. Well as all Know, we can do that via WebView and injectedJavaScript.

Well, once you want to work while the mobile is locked, Your app will go to Pause mode, and as long as web view is a UI thread. Android system will pause the activity.
Moreover, You can not put a UI activity in a "service".

So, and after a long search, I came to the headless browser idea. PhantomJs and others do not support android.
And suddenly I saw this project which uses Chromium as the base.

So I have some questions.

1- Let's say I get a cookie from the normal android WebView. Can I reuse it with this headless browser?
2- Can we use the headless browser as a service in the Android application.
3- Is there any API to talk to, Or How can I communicate with kiwibrowser headless browser from the android service.
4- is there any DEMO opens source android studio project which shows how can we communicate with the headless browser.

I viewed :
https://github.com/kiwibrowser/android/tree/master/headless
but I found no documentation how can I call the API via Android JAVA code. if there is any sample will be a more suitable approach.

Thank you and best regards

**Comment by KaKi87** [comment]
Your request is out of this repository's scope, you can eventually reach out to developers on our [Discord](https://discord.com/invite/b6hVz26) community.

In any case, please post eventual further Kiwi Browser issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
