### ISSUE TITLE
Option to disable ad-blocker by default in incognito tab

### ISSUE THREAD

**Issue by Sajito** [kiwibrowser/android#51]
Hi,

I use incognito tabs quite a lot and I'm looking for a way to disable the built-in ad-blocker by default in incognito tabs, because I use ublock origins, as it gives me better control over the blocked content.

Is it possible to make the state for the built-in ad-blocker persistent for incognito tabs?

Thanks.

**Comment by hjyoung1** [comment]
You can turn off built-in adblocker completely (normal + incognito)
From Setting > Site Settings > Ads
But turning off inbuilt adblocker only for incognito tabs currently not possible.

**Comment by Sajito** [comment]
Thanks, that's exactly what I was looking for. Somehow I couldn't find that setting.
