### ISSUE TITLE
KiWi browser has been officially removed from PlayStore! Rip!

### ISSUE THREAD

**Issue by PranavBhattari** [kiwibrowser/android#52]
![Screenshot from 2019-05-06 14-37-13](https://user-images.githubusercontent.com/32763112/57230004-1a674b00-7037-11e9-9066-4060b59b0af7.png)
This is indeed sad news. Why I don't know? If u don't below me, try searching it in Play store.
Or use official like of play store, it will lead u to nothing.

Probably because kiwi might have violated "Google Play Protect" or something like that.

(screenshot available)

![f](https://user-images.githubusercontent.com/32763112/57229910-dd02bd80-7036-11e9-9a5e-da25f6a21d40.jpg)

**Comment by CHEF-KOCH** [comment]
[Here is the full story including screenshots, background & discussion](https://old.reddit.com/r/Android/comments/bla1tz/kiwi_browser_got_removed_from_play_store/).

![q5TEKAa](https://user-images.githubusercontent.com/727123/57274889-ed4d8380-709c-11e9-87a6-8ba58f6969b6.png)

Developer response:
![vZkZTZE](https://user-images.githubusercontent.com/727123/57274901-f6d6eb80-709c-11e9-9dda-38683519d8e7.png)

The app had over 1 mio. downloads and suddently Google decides that something is wrong with it? That stinks! Each time you upload or update the app google scans it and I believe someone reported it (maybe, just my guess). 

To debunk some claims:
Kiwi does not damage your device or abuse your network. That is nothing but wrong, the source code is here and the browser got already several times reviewed from bigger websites. 

<details>
  <summary>Click to expand</summary>
Thanks goes to tnkforce which provided me with the link/information.
</details>

**Comment by CHEF-KOCH** [comment]
It's back online.

**Comment by PranavBhattari** [comment]
@CHEF-KOCH So no more Youtube background play.
I am happy, its back Play store, but really we are under Google.
To go above Google, please provide in-app update also so that users can play Youtube or any videos in the background.

**Comment by PranavBhattari** [comment]
@CHEF-KOCH Oh my god, u still doesn't know why Google did this to u, not to others.
Because u are not some sort of well-organized organization that can sue Google. 
And your not that famous yet like others (with due respect). Like Firefox, Brave, etc. 

They really got you. I wish u were filthy rich and can grab attention, media support, etc.

I am disappointed. But if I were in your shoes, I would have to the same but until the time, when the app becomes really famous and have like Billion of downloads. That would jack Google in the ass if they even think of touching kiwi. It would grab huge anticompetitive practice worldwide.

**Comment by awsms** [comment]
@CHEF-KOCH 
> the source code is here

No it's not.
