### ISSUE TITLE
Feature Request: Please restore "YouTube playback" at least on xda-labs. It does't have follow Google monopoly rules in that platform.

### ISSUE THREAD

**Issue by PranavBhattarai** [kiwibrowser/android#58]
I loved and adore youtube playback.
I love app update.

But if the update is useless. That also means I am stuck in the old version forever.

Apps like Selinux and Kiwi should think for user preference at least in XDAlabs.

Repeating the same thing is annoying. So, there should be to version onwards:
1: Playstore version (google slavery and dominance) 
2: Xdalabs version (People freedom, open-minded)

**Comment by solokot** [comment]
Absolutely agree! Already more than one developer of really useful applications publishes a flawed version in the Google Market to shut up the "corporation of good" and the full version somewhere else, leaving the links directly in the description on the GP (f.e. https://play.google.com/store/apps/details?id=com.mdnsoft.callsmsmanager&hl=en).

**Comment by hjyoung1** [comment]
https://github.com/kiwibrowser/android/issues/60

**Comment by PranavBhattari** [comment]
@hjyoung1 u are missing the point. For "Playstore" users that zip is a considarable option/choice, they can follow. But for non-play store, like Xdalabs, fdroid, etc the playback should reappear.

**Comment by hjyoung1** [comment]
I asked dev same question. But he already gave his word to google of not pursuing youtube background feature in any way.
So it only seems fair to remove this feature from everywhere. 
But luckily there're other ways like some user ported extension.

**Comment by Athrix05** [comment]
Can anyone tell me what the last version was that supported YouTube playback?

**Comment by akashsdesai** [comment]
Last version supporting YouTube playback is 73.0.3683.90

**Comment by Athrix05** [comment]
Thanks akashsdesai.
Installed and turned off auto-updates for the app!

**Comment by PranavBhattari** [comment]
@hjyoung1 "he already gave his word to google" after what they did to us only and not other browsers!
This is stupidity. He can follow Google rules on PlayStore but it doesn't have to be on xda too.
It's pointless discussing this. I should probably close this issue.

**Comment by Athrix05** [comment]
Do you mean, there are still other browsers on the PlayStore that could
stream Youtube in the background?

**Comment by KaKi87** [comment]
Check out [this userscript](https://greasyfork.org/en/scripts/371641-video-background-play-fix) for YouTube background playback on Kiwi.

For further Kiwi Browser issues, please go to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
