### ISSUE TITLE
Night mode is not perfect

### ISSUE THREAD

**Issue by sqliuchang** [kiwibrowser/android#59]
The pop-up window to log in is still in white background when the night mode is on.
![Night mode](http://wx2.sinaimg.cn/orj360/0060lm7Tly1g2weem6hu0j30u01hcain.jpg)

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
