### ISSUE TITLE
Improved new tab page

### ISSUE THREAD

**Issue by vladimirkosolapov** [kiwibrowser/android#6]
After the **_#enable-ntp-popular-sites_** flag was removed from the chromium, the new tab page is almost _non-customizable_. Almost all sites I visit appear on the new tab page until I clear the history (it would be great if the history could be deleted automatically after each exit from the browser, but about this another time). Recently I found an interesting fork of chromium called [Power Browser](https://www.powerbrowserapp.com) and saw there a nice customizable new tab page. 
<details>
  <summary>Click to expand</summary>
  <img alt="Power Browser NTP" src="https://user-images.githubusercontent.com/34649010/42564217-e3c32aca-8508-11e8-9d77-4b6dfe5d526d.png"/>
</details> 
Also, you can customize this page and disable unnecessary items (for example, most visited sites).
<details>
  <summary>Click to expand</summary>
  <img alt="Power Browser NTP settings" src="https://user-images.githubusercontent.com/34649010/42564567-c2364cec-8509-11e8-92f4-2566c0314923.png"/>
</details>
So, it would be great to make a customizable new tab page in Kiwi Browser.

**Comment by DucAnhNguyen1997** [comment]
I'd love to customized the NTP as well, the current one looks pretty dull. Hope I can add custom news feed source and background changes.
If that's not possible, then do you guys know any New tab page extensions that worked for Kiwi?

**Comment by KaKi87** [comment]
New tab page issues are tracked [here](https://todontp.glitch.me/).
Kiwi Browser issues are now tracked [here](https://github.com/kiwibrowser/src.next/issues).
