### ISSUE TITLE
Flashes white on startup and on new tab page while using Diamond Black theme

### ISSUE THREAD

**Issue by fishstik** [kiwibrowser/android#61]
Night mode: off
Theme: Diamond Black
Using Dark Reader extension

Browser version: 74.0.3729.136
Android 9.0.0

Opening the app flashes a quick white screen before turning dark.
Creating a new tab page flashes a white background before dark reader makes it dark.

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
