### ISSUE TITLE
Provide setting to configure fixed header color instead of changing per-site

### ISSUE THREAD

**Issue by raniesantos** [kiwibrowser/android#63]
Self-explanatory, all in the title.

**Comment by gdgsdg123** [comment]
Let me guess... Are you talking about [this (#23)](https://github.com/kiwibrowser/android/issues/21)?

**Comment by raniesantos** [comment]
That issue is too cluttered, the one who posted it should have made separate issues.

Additional note on my issue.

I know that the Ultra White theme option exists (address bar always white), but I would prefer to set my address bar to always be dark gray (when not in night mode).

**Comment by gdgsdg123** [comment]
> That issue is too cluttered, the one who posted it should have made separate issues for each suggestion.

Maybe... but such schema actually made indexing a lot easier.
<br/>
<br/>
> I know that the Ultra White theme option exists (address bar always white), but I would prefer to set my address bar to always be dark gray (when not in night mode).

So you actually mean Omnibox(address-bar) color customization?..
