### ISSUE TITLE
Dark Reader not working on new tab after changing search engine

### ISSUE THREAD

**Issue by ghost** [kiwibrowser/android#64]
How to reproduce: Disable Kiwi's built-in Night mode if turned on, install and enable Dark Reader, change the search engine to anything other than "Default Search" and restart Kiwi. 

Browser Version: 74.0.3729.136
LineageOS 16.0, Android 9

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
