### ISSUE TITLE
Kiwi native night dark should not turn white text into grey text? It should work like Dark reader extension.

### ISSUE THREAD

**Issue by PranavBhattarai** [kiwibrowser/android#67]
It is painful for it's if "night mode" is not perfect. 
Night mode is not vibrant and comfortable for eyes.

Try to observe these two screenshots:
![Screenshot_20190523-052343](https://user-images.githubusercontent.com/32763112/58215835-45b29100-7ceb-11e9-8e59-0bef3a07b756.jpg)

I love the native dark mode approach but it's not clear. The first screenshot is of kiwi default night mode turned on. The second one is of Dark reader extension working.

![Screenshot_20190523-052408](https://user-images.githubusercontent.com/32763112/58216304-dc984100-7d1d-11e9-8fe9-05cc2650b752.jpg)

Please do not change the color of readable white text into dark grey text. It can damage people's eyes if they make a habit of it.

_This has made the Twitter experience really bad. There are a lot of other issues about this night mode but let's just solve this one for now._

**Comment by hjyoung1** [comment]
You can use 101 contrast setting to get white text + black .
I personally use dark reader + diamond black theme to get best experience.

**Comment by PranavBhattari** [comment]
@hjyoung1 "101" does make some difference by making white text into white text.

But for other colors (esp, blue which denote link), it's not as vibrant as in dark reader.

**Comment by KaKi87** [comment]
Please continue using Dark Reader and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
