### ISSUE TITLE
Option to enable/include Google Sync.

### ISSUE THREAD

**Issue by alecuba16** [kiwibrowser/android#7]
Hello its possible to include it since is useful to remember passwords and bookmarks between smartphone and pc.

**Comment by dimqua** [comment]
It's not possible to any chromium-based browser: https://www.androidpolice.com/2017/01/24/google-shuts-off-chrome-sync-api-third-party-browsers-android-citing-security-vulnerability/

**Comment by MaggiWuerze** [comment]
Google isn't keeping devs from using the feature, just from using the official sync servers. Since you can host your own i would be glad if we could get the option and a way to set the sync url. On desktop it works via start parameters.
