### ISSUE TITLE
Release the source code

### ISSUE THREAD

**Issue by RavetcoFX** [kiwibrowser/android#70]
It's the ethical thing to do, would make myself and others trust this browser, as who knows if you have telemetry built in, and would allow a f-droid version with background play re enabled. if it were open source I would even like to contribute an open-source way of syncing.

**Comment by kingio** [comment]
Do.. you.. know this is the source code?

**Comment by DI555** [comment]
I wanted to post this issue also). Yes it's at least for auditing purposes... .
BUT the author may put it with some partly open licence,- I mean right to see code but not to use it! The goal of it,- Kiwi may be in many free distributions, OSes!
And of course, useful code for share may be as patches like now , with open licence!

**Comment by RavetcoFX** [comment]
> Do.. you.. know this is the source code?

It is not really, there is only one commit with many releases.

**Comment by kingio** [comment]
Yep, i realised it, i tried to build the apk from this repo and all what i get is "raw" Chromium apk with no extensions, and Kiwi references :S

**Comment by wooque** [comment]
it's not just ethical but it's common sense thing to do, how can I use browser of some no name developer if I don't have transparency what browser does, how would I know if kiwi developer is not injecting tracking, keylogging or stealing my credit card info.

**Comment by Laicure** [comment]
Kiwi's source here is sh*t and just for "show".
Kiwi is not open-source.
So I hope headlines in Android news sites remove the *open-source* tag.

**Comment by awsms** [comment]
Kiwi is basically a CLOSED SOURCE spyware which phones home every 5 minutes.

**Comment by dimqua** [comment]
There are a lot of non-free Chromium forks at Google Play Store. Kiwi is just one of them.

**Comment by Laicure** [comment]
Well, coming back to the point in this issue.
The [XDA thread](https://forum.xda-developers.com/android/apps-games/app-kiwi-browser-chromium-adblock-caf-t3797252) of Kiwi says it is.. 
![image](https://user-images.githubusercontent.com/8619566/62026773-83152c80-b20e-11e9-939a-4a6d5f84f535.png)

But this repo doesn't.
Where is the _progression_ on this repo?

**Comment by awsms** [comment]
@Laicure What do you mean ? Kiwi browser is closed source ; if you build this repo you will have a vanilla chromium, nothing more

**Comment by Laicure** [comment]
> @Laicure What do you mean ? Kiwi browser is closed source ; if you build this repo you will have a vanilla chromium, nothing more
> 
> Pretty ironic when his github motto is "Building open technologies for a better world" :)))

I mean, it contradicts Kiwi's XDA thread's _**Progressively open-source**_ note.
And yes, the owner says it is open-source (it is even mentioned on android news sites that Kiwi is open-source but hell's not).
Really, ironic. The developer uses [discord ](https://discord.gg/XyMppQq)for tracking and etc, not even batting an eye on this repo or even his [XDA thread](https://forum.xda-developers.com/android/apps-games/app-kiwi-browser-chromium-adblock-caf-t3797252).

**Comment by Laicure** [comment]
Ugh [update](https://forum.xda-developers.com/showpost.php?p=80233110&postcount=2799)...
Discord is not Github :/

**Comment by dimqua** [comment]
It now says
> Some pieces are open-source at https://github.com/kiwibrowser/android (in particular in privacy_patches)

**Comment by Laicure** [comment]
thanks for looking.
/hmm should be some "stale, non-updating" pieces.

Anyway, I'm done with this.
No more pushing for it to be open, it's futile.

**Comment by jdtechsol** [comment]
> Kiwi is basically a CLOSED SOURCE spyware which phones home every 5 minutes. Switch to [Bromite](https://github.com/bromite/bromite) instead.
> 
> edit: just noticed the dev doesn't even give a shit about his git, never replied to anyone (look at the closed issues)

phones home every 5 minutes? Do you have proof of this?

**Comment by kiwibrowser** [comment]
Hi,

Thanks for your patience, there were lot of considerations before actually open-sourcing the project.
Fixed, now 100% open-source and development moved to public git (which becomes the main central repo) - https://github.com/kiwibrowser/src
