### ISSUE TITLE
Another episode of default night mode went wrong

### ISSUE THREAD

**Issue by PranavBhattarai** [kiwibrowser/android#71]
![Screenshot_20190526-092519](https://user-images.githubusercontent.com/32763112/58380065-c0093c80-7f9b-11e9-9aa8-cb697c487048.jpg)

![Screenshot_20190526-153702](https://user-images.githubusercontent.com/32763112/58380085-02327e00-7f9c-11e9-97a0-167fd5b00aa4.jpg)

PS: Don't override graphical images.

**Comment by hjyoung1** [comment]
I recommend you to report this or any other issues you're having on kiwi discord server. 
https://discordapp.com/invite/XyMppQq
Devloper is way more active there. This repo is wip.

**Comment by PranavBhattari** [comment]
@hjyoung1 github is more "standard way" for reporting. 
If I have used Discord for other things too than I would have installed it.
But I don't use it. Do u want me to install another app just to report issue and bug of kiwi?
I think I am going to go with github.
If a developer is not active on this platform then, he delete github repo.
What's the point if no one is listening, maintaining things here?!

**Comment by hjyoung1** [comment]
I agree with you. Github is definitely better for bug reports enhancement etc..
As i said this repo is work in progress currently this repo is used as only alternate mirror for kiwi releases. 
There's no other activity from developer (yet)

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
