### ISSUE TITLE
Secure Quietness

### ISSUE THREAD

**Issue by DI555** [kiwibrowser/android#72]
First of all, let me apprecciate the author with great leap, the extensionable mobile browser!!! We waited it so much!(after garbaged mobile ya_browser)
Thank you so much! Keep it up!

I have one feature waited in it. Its Secure Quietness!
  Please, cut off all RLZ bunch(module) code away! (We may discuss about some others modules later as they're not so dangerous as this)
  Delete all connecting with browser id(including collecting system/device data), please!
  And, please, elimimate all urls(mainly google ones) from code, except needed ones(validating sites etc.) Or if not possible, loop them all - place localhost/127.0.0.1 instead them all!
 
Many thanks in advance!

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
