### ISSUE TITLE
Kiwi-20190526154122 Feedback

### ISSUE THREAD

**Issue by shui288** [kiwibrowser/android#73]
Kiwi-20190526154122 Feedback

1. Bookmarks cannot move up and down in the same folder. Please add all selected options.
2. Unable to install extensions with RootExplorer
3. Box 1 and 3 vertical points are enlarged a little. Just like yandex browser.
4. The extension of the menu should be unified into the extension.

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store, post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues), and always create individual posts for each bug report or feature request.
