### ISSUE TITLE
[Extension] auto selecting the best resolution for YouTube 

### ISSUE THREAD

**Issue by LifeIsStrange** [kiwibrowser/android#74]
Hi!
Kiwi now has an extension for playing YouTube on the background https://github.com/kiwibrowser/android/issues/60 , but YouTube on kiwi is still sub-par to the YouTube app because we can choose a resolution and the default one is really bad.
Ideally the resolution should be the one of the smartphone screen. 

Btw does anyone know an alternative website that scrap YouTube content but has a better mobile interface?
There could even be an extension (or stylish) that inject CSS.

**Comment by DI555** [comment]
It't not the browser issue. If you switch-on to use cookies on youtube,- it remembers you choice with resolution, no need even lo login.
