### ISSUE TITLE
[Feature request] ship on the play store kiwi nightly

### ISSUE THREAD

**Issue by LifeIsStrange** [kiwibrowser/android#75]
I would really love to see kiwi dev for chromium dev and kiwi canary for chromium canary!
I always browse on canary, it's rarely buggy and has more features and more performance than chromium stable :)

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
