### ISSUE TITLE
Why has kiwi a lower html5test score than chrome stable? 

### ISSUE THREAD

**Issue by LifeIsStrange** [kiwibrowser/android#76]
Chrome stable is detected by www.html5test.com as release 74 0f chromium and detect kiwi as 74 too.
But kiwi has a score of 525 while chrome has 532.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
