### ISSUE TITLE
Lagging on flipboard mobile site

### ISSUE THREAD

**Issue by mill6791** [kiwibrowser/android#77]
Starting with the Andromeda release and all releases after the mobile site flipboard lags every time I scroll. I have tried the site on other browsers and it works fine. On the kappa release there is virtually no lag.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
