### ISSUE TITLE
Different Method to choose the download directory

### ISSUE THREAD

**Issue by NotesOfReality** [kiwibrowser/android#8]
Could you please change the method to select the download directory to the same one used by "ADM" ( https://play.google.com/store/apps/details?id=com.dv.adm&hl=en ) and "AllBackupRestore" ( https://play.google.com/store/apps/details?id=com.dv.adm&hl=en ) , they use the android default file manager to select a directory in internal or external sdcard.Here's a very short video for a clearer idea https://drive.google.com/open?id=1aPQrr4m31LVzmW3kjFQSIxzlfyqChy8g . 
Thanks in advance.

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
