### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by rahul56788** [kiwibrowser/android#80]
Notification popup is not displaying for Facebook and other websites and I couldn't get notifications .
Notification popup which asks for allow or block notifications is not being displayed even though I tried it to open it from Facebook settings .I changes user agent then also this problem persists.
Not only with Facebook, but with other websites also same issue is happening and notifications are not working.
I turned off all extensions,allowed ads and all popus ,enabled java script, cookies then also notifications are not working and allow or block notification permission is not being displayed.
Please fix it.
I mailed you regarding this multiple times on your email but still there's no response.
Please fix this issue soon..

**Comment by g180** [comment]
I'm having the same trouble.

Kiwi Browser 77.0.3865.92
Android 8.0.0
d-01k Build/HUWEIHDN-L1J

This was reported previously: https://github.com/kiwibrowser/android/issues/46

**Comment by Sekers** [comment]
Try going to kiwi://settings/content/notifications and adding in the site you need.

An example would be https://m.facebook.com/

**Comment by g180** [comment]
> Try going to kiwi://settings/content/notifications and adding in the site you need.
> 
> An example would be https://m.facebook.com/

Thanks Sekers, the setting seems working for now.

**Comment by premkumarmahenderker** [comment]
> 
> 
> Try going to kiwi://settings/content/notifications and adding in the site you need.
> 
> An example would be https://m.facebook.com/

This is so hiddenly awesome. Seems there's no UI interface for adding notifications.
