### ISSUE TITLE
addEventListener with useCapture=true is not working

### ISSUE THREAD

**Issue by vshabanov** [kiwibrowser/android#84]
Hi, this code does nothing when I click anywhere in the document:
```js
document.addEventListener('click', () => alert('clicked!'), {capture:true})
```
Code works if I set `capture` to `false` but I need `capture` to be `true` for my use case.

[BazQux Reader](https://bazqux.com) (RSS/Twitter/Facebook feed reader) doesn't work correctly in Kiwi browser due to this.

**Comment by woncode** [comment]
you mean you want recieve the click event in first of all, but the click event not happen, or the event is recieved after its child-element?

**Comment by vshabanov** [comment]
Click event not happen at all. No alert box with "clicked!" when I click anywhere in the document.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
