### ISSUE TITLE
Many URL players cannot play in full screen

### ISSUE THREAD

**Issue by hehky** [kiwibrowser/android#87]
Many URL players cannot play in full screen 

like   http://m.dygang.net

https://m.kankanwu.com/Action/diyunanjuexuehuanghoujueqi/player-0-0.html

**Comment by hjyoung1** [comment]
Post those url where you're having this problem.
Some screenshots of problem would be nice too.

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
