### ISSUE TITLE
Kiwi-20190627081012.apk------ Feedback

### ISSUE THREAD

**Issue by shui288** [kiwibrowser/android#89]
Kiwi-20190627081012.apk------ Feedback:
1. Bookmarks cannot move up and down
2. The menu display extension program is too messy, it is better to directly install the installed extension into the menu extension (like the extension in the menu of Yandex browser)
3.RootExplorer_ file manager still can not install extensions

**Comment by KaKi87** [comment]
Please check out the latest version from the Play Store, post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues), and always create individual posts for each bug report or feature request.
