### ISSUE TITLE
Fix capitalisation of DuckDuckGo

### ISSUE THREAD

**Issue by tagawa** [kiwibrowser/android#90]
Hi there. Daniel from DuckDuckGo here. Thank you for including us as a search engine option within Kiwi Browser.

One request: Please could you capitalise the name as "DuckDuckGo" and remove the "yahoo.net" mention? We currently get our search results [from a variety of sources](https://help.duckduckgo.com/duckduckgo-help-pages/results/sources/), not just Yahoo.

![kiwi-browser_search-engines](https://user-images.githubusercontent.com/94173/60722496-a0f9b500-9f20-11e9-8f34-b215c29a6e2a.jpg)

**Comment by awsms** [comment]
@tagawa the dev never goes on github, you should mail him

**Comment by tagawa** [comment]
Hi @awsms. Thanks for checking. He emailed me and this is working on it for the upcoming release, so we should be able to close this soon.
