### ISSUE TITLE
JavaScript Date issue - dateToConvert.toLocaleString

### ISSUE THREAD

**Issue by mrjackwills** [kiwibrowser/android#97]
I noticed that whilst testing a front end application, written with Vue, on kiwi browser on Android 8, results in an issue with date formatting using JavaScript. This bug is only found, during my testing, in Kiwi browser, and Internet Explorer 11 on Windows.

The "buggy" code works as expected on Android + Windows Chrome & Firefox, as well as Windows Edge & Edge Dev

using this code, const result is undefined 

```
const dateToConvert= new Date('2019-07-18');

const result = String(dateToConvert.toLocaleString('en-GB', { weekday: 'long', month: 'long', day: '2-digit',  timeZone: 'UTC' }).split(',')[1]);
```
the work around is to use the method below;

```
const dateToConvert= new Date('2019-07-18');

const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const result = `${dateToConvert.getUTCDate() } ${months[dateToConvert.getUTCMonth()]}`;
```

**Comment by KaKi87** [comment]
Please retry with the latest version from the Play Store and post eventual further issues to [kiwibrowser/src.next](https://github.com/kiwibrowser/src.next/issues).
